software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog Class Reference
Public Member Functions
def __init__
def aesmodeChanged (self, indx)
def setKeyLength (self, klen)
def inTextChanged
Public Attributes
outmode
indata
keysched
outkey
inprnd
Constructor & Destructor Documentation
def software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.__init__ (self, parent = None)
    def __init__(self, parent=None):
        super(KeyScheduleDialog, self).__init__(parent)
        layout = QVBoxLayout()
        self.setLayout(layout)
        self.outmode = QComboBox()
        self.outmode.addItem("AABBCC...EEFF", ["", ""])
        self.outmode.addItem("AA:BB:CC...EE:FF", ["", ":"])
        self.outmode.addItem("AA BB CC...EE FF", ["", " "])
        self.outmode.addItem("AA,BB,CC...EE,FF", ["", ","])
        self.outmode.addItem("0xAA, 0xBB, 0xCC... 0xEE, 0xFF", ["0x", ", "])
        self.outmode.currentIndexChanged.connect(self.inTextChanged)
        self.indata = QtFixes.QLineEdit("")
        self.indata.setFont(QFont("Courier"))
        self.keysched = QTextEdit("")
        self.keysched.setFont(QFont("Courier"))
        self.outkey = QtFixes.QLineEdit("")
        self.outkey.setReadOnly(True)
        self.outkey.setFont(QFont("Courier"))
        outmodeL = QHBoxLayout()
        outmodeL.addWidget(QLabel("Format:"))
        outmodeL.addWidget(self.outmode)
        outmodeL.addStretch()
        self.inprnd = QComboBox()
        self.inprnd.currentIndexChanged.connect(self.inTextChanged)
        self.setKeyLength(128)
        indataL = QHBoxLayout()
        indataL.addWidget(QLabel("Key:"))
        indataL.addWidget(self.indata)
        indataL.addWidget(self.inprnd)
        self.indata.textChanged.connect(self.inTextChanged)
        outdataL = QHBoxLayout()
        outdataL.addWidget(QLabel("Key:"))
        outdataL.addWidget(self.outkey)
        gbIndata = QGroupBox("Input Known Key")
        gbIndata.setLayout(indataL)
        layout.addWidget(gbIndata)
        gbOutdata = QGroupBox("Output Desired Key")
        outdataTotalL = QVBoxLayout()
        outdataTotalL.addLayout(outmodeL)
        outdataTotalL.addLayout(outdataL)
        gbOutdata.setLayout(outdataTotalL)
        layout.addWidget(gbOutdata)
        gbKeySched = QGroupBox("Full Key Schedule")
        keyschedL = QVBoxLayout()
        keyschedL.addWidget(self.keysched)
        gbKeySched.setLayout(keyschedL)
        layout.addWidget(gbKeySched)
        self.setWindowTitle("AES-128/AES-256 Key Schedule Calculator")
        self.setObjectName("AES Key Schedule")
        # try:
        self.setWindowIcon(QIcon(":/images/cwiconA.png"))
        # except:
        # pass
Member Function Documentation
def software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.aesmodeChanged (self, indx)
References software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.setKeyLength().
    def aesmodeChanged(self, indx):
        self.setKeyLength(self.aesmode.itemData(indx))
def software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.inTextChanged (self, data = None)
References software.chipwhisperer.common.utils.util.hexstr2list(), software.chipwhisperer.analyzer.models.aes.key_schedule.keyScheduleRounds(), and software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.setKeyLength().
    def inTextChanged(self, data=None):
        data = self.indata.text()
        try:
            newdata = hexstr2list(data)
            if len(newdata) != 16 and len(newdata) != 32:
                err = "ERR: Len=%d: %s" % (len(newdata), newdata)
                self.outkey.setText(err)
                self.keysched.setText(err)
            else:
                if len(newdata) == 16:
                    self.setKeyLength(128)
                elif len(newdata) == 32:
                    self.setKeyLength(256)
                #Read settings
                delim = self.outmode.itemData(self.outmode.currentIndex())
                desired = 0
                inpround = self.inprnd.itemData(self.inprnd.currentIndex())
                key = newdata
                # Get initial key
                result = keyScheduleRounds(key, inpround, desired)
                if len(key) == 32:
                    result.extend(keyScheduleRounds(key, inpround, desired + 1))
                rstr = ["%02x" % t for t in result]
                rstr = (delim[1] + delim[0]).join(rstr)
                rstr = delim[0] + rstr
                self.outkey.setText(rstr)
                # Get entire key schedule
                if len(key) == 16:
                    rnds = 10
                elif len(key) == 32:
                    rnds = 14
                totalrndstr = ""
                for r in range(0, rnds+1):
                    result = keyScheduleRounds(key, inpround, r)
                    rstr = ["%02x" % t for t in result]
                    rstr = (delim[1] + delim[0]).join(rstr)
                    rstr = delim[0] + rstr
                    totalrndstr += rstr + "\n"
                self.keysched.setText(totalrndstr)
        except ValueError:
            self.outkey.setText("ERR in HEX: %s" % data)
def software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.setKeyLength (self, klen)
Referenced by software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.aesmodeChanged(), and software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.inTextChanged().
    def setKeyLength(self, klen):
        pi = self.inprnd.currentIndex()
        self.inprnd.blockSignals(True)
        if klen == 128:
            self.inprnd.clear()
            self.inprnd.addItem("0 (Initial Enc.)", 0)
            self.inprnd.addItem("10 (Initial Dec.)", 10)
        elif klen == 256:
            self.inprnd.clear()
            self.inprnd.addItem("0/1 (Initial Enc.)", 0)
            self.inprnd.addItem("13/14 (Initial Dec.)", 13)
        else:
            raise ValueError("Invalid keylength: %d" % klen)
        if pi > -1:
            self.inprnd.setCurrentIndex(pi)
        self.inprnd.blockSignals(False)
Member Data Documentation
software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.indata
software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.inprnd
software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.keysched
software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.outkey
software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.outmode
The documentation for this class was generated from the following file:
KeyScheduleDialog.py