software.chipwhisperer.analyzer.attacks.models.AES128_8bit Namespace Reference
Functions
def processKnownKey (setting, inpkey)
def leakage (pt, ct, guess, bnum, setting, state)
def getHW (var)
def VccToGnd (var)
def xtime (a)
Variables
int LEAK_HW_SBOXOUT_FIRSTROUND = 1
int LEAK_HD_LASTROUND_STATE = 2
int LEAK_HD_SBOX_IN_OUT = 3
int LEAK_HD_SBOX_IN_SUCCESSIVE = 4
int LEAK_HD_SBOX_OUT_SUCCESSIVE = 5
int LEAK_HW_INVSBOXOUT_FIRSTROUND = 6
tuple leakagemodels = util.DictType()
int numSubKeys = 16
int permPerSubkey = 256
list HW8Bit
Generate this table with: HW = [] for n in range(0, 256): HW = HW + [bin(n).count(`1`)].
list SHIFT = []
list INVSHIFT = [0, 5, 10, 15, 4, 9, 14, 3, 8, 13, 2, 7, 12, 1, 6, 11]
Function Documentation
def software.chipwhisperer.analyzer.attacks.models.AES128_8bit.getHW (var)
Given a variable, return the hamming weight (number of 1's)
Referenced by software.chipwhisperer.analyzer.attacks.profiling_algorithms.template.ProfilingTemplate.addTraces(), software.chipwhisperer.analyzer.utils.Partition.PartitionHDLastRound.getPartitionNum(), software.chipwhisperer.analyzer.utils.Partition.PartitionHWIntermediate.getPartitionNum(), and software.chipwhisperer.analyzer.attacks.models.AES128_8bit.leakage().
def getHW(var):
    """Given a variable, return the hamming weight (number of 1's)"""
    return HW8Bit[var]
def software.chipwhisperer.analyzer.attacks.models.AES128_8bit.leakage (pt, ct, guess, bnum, setting, state)
References software.chipwhisperer.analyzer.attacks.models.AES128_8bit.getHW(), software.chipwhisperer.analyzer.models.aes.funcs.inv_sbox(), and software.chipwhisperer.common.utils.aes_tables.sbox.
def leakage(pt, ct, guess, bnum, setting, state):
    if setting == LEAK_HW_SBOXOUT_FIRSTROUND:
        # Classic HW of S-Box output
        return getHW(sbox(pt[bnum] ^ guess))
    elif setting == LEAK_HW_INVSBOXOUT_FIRSTROUND:
        # HW Leakage of inverse S-Box (AES Decryption)
        return getHW(inv_sbox(pt[bnum] ^ guess))
    elif setting == LEAK_HD_LASTROUND_STATE:
        # HD Leakage of AES State between 9th and 10th Round
        # Used to break SASEBO-GII / SAKURA-G
        st10 = ct[INVSHIFT[bnum]]
        st9 = inv_sbox(ct[bnum] ^ guess)
        return getHW(st9 ^ st10)
    elif setting == LEAK_HD_SBOX_IN_OUT:
        # Leakage from HD of S-Box input to output
        st1 = pt[bnum] ^ guess
        st2 = sbox(st1)
        return getHW(st1 ^ st2)
    elif setting == LEAK_HD_SBOX_IN_SUCCESSIVE:
        pass
    elif setting == LEAK_HD_SBOX_OUT_SUCCESSIVE:
        pass
    else:
        raise ValueError("Invalid setting: %s" % str(setting))
def software.chipwhisperer.analyzer.attacks.models.AES128_8bit.processKnownKey (setting, inpkey)
References software.chipwhisperer.analyzer.models.aes.key_schedule.keyScheduleRounds().
def processKnownKey(setting, inpkey):
    if setting == LEAK_HD_LASTROUND_STATE:
        return keyScheduleRounds(inpkey, 0, 10)
    return inpkey
def software.chipwhisperer.analyzer.attacks.models.AES128_8bit.VccToGnd (var)
Convert from number of 1's to number of 0's... used when shunt inserted in GND path
def VccToGnd(var):
    """Convert from number of 1's to number of 0's... used when shunt inserted in GND path"""
    return 8 - var
# TODO: Use this
def software.chipwhisperer.analyzer.attacks.models.AES128_8bit.xtime (a)
xtime operation
def xtime(a):
    """xtime operation"""
    a %= 0x100
    b = 0
    if a & 0x80:
        b = 0x1b
    a <<= 1
    a &= 0xff
    a ^= b
    return a
Variable Documentation
list software.chipwhisperer.analyzer.attacks.models.AES128_8bit.HW8Bit
Initial value:
= [0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, 4, 1, 2, 2, 3, 2, 3, 3,
          4, 2, 3, 3, 4, 3, 4, 4, 5, 1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4,
          4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 1, 2, 2, 3, 2,
          3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5,
          4, 5, 5, 6, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4,
          5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7, 1, 2, 2, 3, 2, 3, 3, 4, 2, 3,
          3, 4, 3, 4, 4, 5, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 2,
          3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6, 3, 4, 4, 5, 4, 5, 5, 6,
          4, 5, 5, 6, 5, 6, 6, 7, 2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5,
          6, 3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7, 3, 4, 4, 5, 4, 5,
          5, 6, 4, 5, 5, 6, 5, 6, 6, 7, 4, 5, 5, 6, 5, 6, 6, 7, 5, 6, 6, 7, 6,
          7, 7, 8]
Generate this table with: HW = [] for n in range(0, 256): HW = HW + [bin(n).count(`1`)].
list software.chipwhisperer.analyzer.attacks.models.AES128_8bit.INVSHIFT = [0, 5, 10, 15, 4, 9, 14, 3, 8, 13, 2, 7, 12, 1, 6, 11]
int software.chipwhisperer.analyzer.attacks.models.AES128_8bit.LEAK_HD_LASTROUND_STATE = 2
int software.chipwhisperer.analyzer.attacks.models.AES128_8bit.LEAK_HD_SBOX_IN_OUT = 3
int software.chipwhisperer.analyzer.attacks.models.AES128_8bit.LEAK_HD_SBOX_IN_SUCCESSIVE = 4
int software.chipwhisperer.analyzer.attacks.models.AES128_8bit.LEAK_HD_SBOX_OUT_SUCCESSIVE = 5
int software.chipwhisperer.analyzer.attacks.models.AES128_8bit.LEAK_HW_INVSBOXOUT_FIRSTROUND = 6
int software.chipwhisperer.analyzer.attacks.models.AES128_8bit.LEAK_HW_SBOXOUT_FIRSTROUND = 1
tuple software.chipwhisperer.analyzer.attacks.models.AES128_8bit.leakagemodels = util.DictType()
int software.chipwhisperer.analyzer.attacks.models.AES128_8bit.numSubKeys = 16
int software.chipwhisperer.analyzer.attacks.models.AES128_8bit.permPerSubkey = 256
list software.chipwhisperer.analyzer.attacks.models.AES128_8bit.SHIFT = []