software.chipwhisperer.capture.scopes.PicoScope Namespace Reference
Classes
class PicoScope
class PicoScopeInterface
Functions
def __init__
def updateSampleRateFreq
def updateSampleRateFreqUI (self)
def con (self)
def dis (self)
def updateCurrentSettings
def arm (self)
def capture (self)
Variables
string _name = 'Pico Scope'
ps
dataUpdated
_faketimer
datapoints
Function Documentation
def software.chipwhisperer.capture.scopes.PicoScope.__init__ (self, parentParam = None, psClass = None)
    def __init__(self, parentParam=None, psClass=None):
        ScopeTemplate.__init__(self, parentParam)
        self.ps = psClass
        self.dataUpdated = util.Signal()
        chlist = {}
        for t in self.ps.CHANNELS:
            if self.ps.CHANNELS[t] < self.ps.CHANNELS['MaxChannels']:
                chlist[t] = self.ps.CHANNELS[t]
        # Rebuild channel range as string + api value
        chRange = util.DictType()
        for key in sorted(self.ps.CHANNEL_RANGE):
            chRange[ key['rangeStr'] ] = key['rangeV']
        self.params.addChildren([
            {'name':'Trace Measurement', 'type':'group', 'children':[
                {'name':'Source', 'key':'tracesource', 'type':'list', 'values':chlist, 'value':0, 'set':
      self.updateCurrentSettings},
                {'name':'Probe Att.', 'key':'traceprobe', 'type':'list', 'values':{'1:1':1, '1:10':10}, '
      value':1, 'set':self.updateCurrentSettings},
                {'name':'Coupling', 'key':'tracecouple', 'type':'list', 'values':self.ps.CHANNEL_COUPLINGS,
       'value':0, 'set':self.updateCurrentSettings},
                {'name':'Y-Range', 'key':'traceyrange', 'type':'list', 'values':chRange, 'value':1.0, 'set'
      :self.updateCurrentSettings},
            ]},
            {'name':'Trigger', 'type':'group', 'children':[
                {'name':'Source', 'key':'trigsource', 'type':'list', 'values':chlist, 'value':1, 'set':
      self.updateCurrentSettings},
                {'name':'Probe Att.', 'key':'trigprobe', 'type':'list', 'values':{'1:1':1, '1:10':10}, '
      value':10, 'set':self.updateCurrentSettings},
                {'name':'Coupling', 'key':'trigcouple', 'type':'list', 'values':self.ps.CHANNEL_COUPLINGS,
      'value':1, 'set':self.updateCurrentSettings},
                {'name':'Y-Range', 'key':'trigrange', 'type':'list', 'values':chRange, 'value':5.0, 'set':
      self.updateCurrentSettings},
                {'name':'Trigger Direction', 'key':'trigtype', 'type':'list', 'values':
      self.ps.THRESHOLD_TYPE, 'value':2, 'set':self.updateCurrentSettings},
                {'name':'Trigger Level', 'key':'triglevel', 'type':'float', 'step':1E-2, 'siPrefix':True, '
      suffix':'V', 'limits':(-5, 5), 'value':0.5, 'set':self.updateCurrentSettings},
            ]},
            {'name':'Sample Rate', 'key':'samplerate', 'type':'int', 'step':1E6, 'limits':(10000, 5E9), '
      value':100E6, 'set':self.updateSampleRateFreq, 'siPrefix':True, 'suffix': 'S/s'},
            {'name':'Sample Length', 'key':'samplelength', 'type':'int', 'step':5000, 'limits':(1, 500E6),
      'value':5000, 'set':self.updateSampleRateFreq},
            {'name':'Sample Offset', 'key':'sampleoffset', 'type':'int', 'step':1000, 'limits':(0, 100E6),
      'value':0, 'set':self.updateSampleRateFreq},
        ])
            
def software.chipwhisperer.capture.scopes.PicoScope.arm (self)
    def arm(self):
        self.ps.runBlock()
        
def software.chipwhisperer.capture.scopes.PicoScope.capture (self)
    def capture(self):
        while(self.ps.isReady() == False): time.sleep(0.01)
        data = self.ps.getDataV(self.findParam('tracesource').value(), self.findParam('samplelength').value
      (), startIndex=self.findParam('sampleoffset').value(), returnOverflow=True)
        if data[1] is True:
            print "WARNING: OVERFLOW IN DATA"
        self.datapoints = data[0]
        self.dataUpdated.emit(self.datapoints, 0)
        # No timeout?
        return False
def software.chipwhisperer.capture.scopes.PicoScope.con (self)
Referenced by software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.connectScope(), and software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.connectTarget().
    def con(self):
        self.ps.open()
        self.updateCurrentSettings()
def software.chipwhisperer.capture.scopes.PicoScope.dis (self)
Referenced by software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.disconnectScope(), software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.disconnectTarget(), software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.setScope(), and software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.setTarget().
    def dis(self):
        self.ps.close()
    
def software.chipwhisperer.capture.scopes.PicoScope.updateCurrentSettings (self, ignored = False)
    def updateCurrentSettings(self, ignored=False):
        if self.ps.handle is None: return
        try:
            # Turn off all channels
            for c in self.ps.CHANNELS:
                self.ps.setChannel(c, enabled=False)
        except IOError:
            pass
        try:
            # Trace Channel
            TraceCh = self.findParam('tracesource').value()
            TraceCo = self.findParam('tracecouple').value()
            TraceY = self.findParam('traceyrange').value()
            TraceP = self.findParam('traceprobe').value()
            self.ps.setChannel(channel=TraceCh, coupling=TraceCo, VRange=TraceY, probeAttenuation=TraceP,
      enabled=True)
            # Trigger Channel
            TrigCh = self.findParam('trigsource').value()
            TrigCo = self.findParam('trigcouple').value()
            TrigY = self.findParam('trigrange').value()
            TrigP = self.findParam('trigprobe').value()
            self.ps.setChannel(channel=TrigCh, coupling=TrigCo, VRange=TrigY, probeAttenuation=TrigP,
      enabled=True)
            # Trigger
            self.ps.setSimpleTrigger(TrigCh, self.findParam('triglevel').value(), direction=self.findParam(
      'trigtype').value(), timeout_ms=1000)
            self.updateSampleRateFreq()
        except IOError, e:
            raise IOError("Caught Error: %s" % str(e))
def software.chipwhisperer.capture.scopes.PicoScope.updateSampleRateFreq (self, ignored = None)
    def updateSampleRateFreq(self, ignored=None):
        if self.ps.handle is not None:
            paramSR = self.findParam('samplerate')
            paramSL = self.findParam('samplelength')
            self.ps.setSamplingFrequency(paramSR.value(), paramSL.value() + self.findParam('sampleoffset').
      value(), 1)
            #Need this callback as otherwise the setValue() is overwritten when the user toggles off, might
       be fixed
            #with Adriel's new parameterTypes, will have to test again
            self._faketimer = timer.runTask(self.updateSampleRateFreqUI, 0.1, True, True)
def software.chipwhisperer.capture.scopes.PicoScope.updateSampleRateFreqUI (self)
    def updateSampleRateFreqUI(self):
        paramSR = self.findParam('samplerate')
        paramSL = self.findParam('samplelength')
        if self.ps.sampleRate != paramSR.value():
            paramSR.setValue(self.ps.sampleRate)
        newSL = min(self.ps.maxSamples, paramSL.value())
        if newSL != paramSL.value():
            paramSL.setValue(newSL)
Variable Documentation
software.chipwhisperer.capture.scopes.PicoScope._faketimer
string software.chipwhisperer.capture.scopes.PicoScope._name = 'Pico Scope'
software.chipwhisperer.capture.scopes.PicoScope.datapoints
software.chipwhisperer.capture.scopes.PicoScope.dataUpdated
software.chipwhisperer.capture.scopes.PicoScope.ps