software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI Class Reference
Public Member Functions
def __init__ (self, api)
def loadExtraModules (self)
def addToolbarItems (self, toolbar)
def addToolMenuItems (self)
def doAnalysis (self)
def addSettingsDocks (self)
def tracesChanged (self)
Static Public Member Functions
def getInstance ()
Public Attributes
keyScheduleDialog
attackScriptGen
traceExplorerDialog
traceExplorerAct
aesScheduleAct
settingsScriptDock
settingsPreprocessingDock
settingsAttackDock
settingsPostProcessingDock
settingsResultsDock
Detailed Description
Main ChipWhisperer Analyzer GUI Window Class.
This is a front-end to the CWCoreAPI.
Constructor & Destructor Documentation
def software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.__init__ (self, api)
References software.chipwhisperer.common.ui.CWMainGUI.CWMainGUI.addExampleScripts().
    def __init__(self, api):
        super(CWAnalyzerGUI, self).__init__(api, name="ChipWhisperer" + u"\u2122" + " Analyzer " +
      CWCoreAPI.__version__, icon="cwiconA")
        self.addExampleScripts(pluginmanager.getPluginsInDictFromPackage("chipwhisperer.analyzer.scripts",
      False, False, self))
        CWAnalyzerGUI.instance = self
        self.attackScriptGen.reloadScripts()
Member Function Documentation
def software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.addSettingsDocks (self)
    def addSettingsDocks(self):
        self.settingsScriptDock = self.addSettings(self.attackScriptGen.scriptParamTree,
      "Script")
        self.settingsPreprocessingDock = self.addSettings(
      self.attackScriptGen.preprocessingParamTree, "Preprocessing")
        self.settingsAttackDock = self.addSettings(self.attackScriptGen.attackParamTree,
      "Attack")
        self.settingsPostProcessingDock = self.addSettings(
      self.attackScriptGen.postprocessingParamTree, "Postprocessing")
        self.settingsResultsDock = self.addSettings(ResultsBase.getParamTree(), "Results
      ")
        # Load all ActiveTraceObservers
        self.windowMenu.addSeparator()
        for k, v in ResultsBase.getClasses().iteritems():
            ResultsBase.createNew(k)
        self.tabifyDocks(self.resultDocks)
        self.tabifyDocks([self.settingsScriptDock, self.
      settingsPreprocessingDock, self.settingsAttackDock,
                          self.settingsPostProcessingDock, self.
      settingsResultsDock])
        self.attackScriptGen.editorDocks()
def software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.addToolbarItems (self, toolbar)
References software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.doAnalysis().
    def addToolbarItems(self, toolbar):
        attack = QAction(QIcon(':/images/attack.png'), 'Start Attack', self)
        attack.triggered.connect(self.doAnalysis)
        toolbar.addAction(attack)
def software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.addToolMenuItems (self)
    def addToolMenuItems(self):
        self.traceExplorerAct = QAction('Trace Explorer', self, statusTip='Get information
       on traces',
                                        triggered=self.traceExplorerDialog.show)
        self.toolMenu.addAction(self.traceExplorerAct)
        self.aesScheduleAct = QAction('AES Key Schedule', self, statusTip='Show AES Key
       Schedule calculator',
                                      triggered=self.keyScheduleDialog.show)
        self.toolMenu.addAction(self.aesScheduleAct)
def software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.doAnalysis (self)
Called when the 'Do Analysis' button is pressed
References software.chipwhisperer.common.ui.CWMainGUI.CWMainGUI.updateStatusBar().
Referenced by software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.addToolbarItems().
    def doAnalysis(self):
        """Called when the 'Do Analysis' button is pressed"""
        if self.api.project().traceManager().numTraces() == 0:
            ret = QMessageBox.question(self, "Attack Error", "No traces enabled in project.\nOpen Trace
       Manager?", QMessageBox.Yes | QMessageBox.No)
            if ret == QMessageBox.Yes:
                self.traceManagerDialog.show()
            return
        self.updateStatusBar("Executing analyzis...")
        self.api.runScriptModule(self.attackScriptGen.setupScriptModule())
        self.updateStatusBar("Analysis completed")
def software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.getInstance () [static]
    def getInstance():
        return CWAnalyzerGUI.instance
def software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.loadExtraModules (self)
    def loadExtraModules(self):
        self.keyScheduleDialog = KeyScheduleDialog(self)
        self.attackScriptGen = AttackScriptGen(None, self)
        self.traceExplorerDialog = TraceExplorerDialog(self)
        self.traceExplorerDialog.scriptsUpdated.connect(self.attackScriptGen.reloadScripts)
        self.traceExplorerDialog.runScriptFunction.connect(self.attackScriptGen.runScriptFunction)
        self.attackScriptGen.utilList = [self.traceExplorerDialog]
def software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.tracesChanged (self)
Traces changed due to loading new project or adjustment in trace manager,
so adjust limits displayed and re-plot the new input trace
    def tracesChanged(self):
        """Traces changed due to loading new project or adjustment in trace manager,
        so adjust limits displayed and re-plot the new input trace"""
        self.attackScriptGen.reloadScripts()
Member Data Documentation
software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.aesScheduleAct
software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.attackScriptGen
software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.keyScheduleDialog
software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.settingsAttackDock
software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.settingsPostProcessingDock
software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.settingsPreprocessingDock
software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.settingsResultsDock
software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.settingsScriptDock
software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.traceExplorerAct
software.chipwhisperer.analyzer.ui.CWAnalyzerGUI.CWAnalyzerGUI.traceExplorerDialog
The documentation for this class was generated from the following file:
CWAnalyzerGUI.py