software.chipwhisperer.common.utils.util Namespace Reference
Classes
class Observable
class Signal
Functions
def getRootDir ()
def copyFile
def strippedName (fullFileName)
def appendAndForwardErrorMessage (msg, e)
def list2hexstr
def hexstr2list (data)
def strListToList (strlist)
def convert_to_str (data)
def hexStrToByteArray (hexStr)
def getPyFiles (dir)
def setUIupdateFunction (func)
def updateUI ()
Variables
DictType = OrderedDict
_uiupdateFunction = None
Function Documentation
def software.chipwhisperer.common.utils.util.appendAndForwardErrorMessage (msg, e)
def appendAndForwardErrorMessage(msg, e):
    raise type(e)(msg + "\n -> " + str(e))
def software.chipwhisperer.common.utils.util.convert_to_str (data)
Converts all dictionary elements to string type - similar to what ConfigObj will
be doing when it saves and loads the data.
def convert_to_str(data):
    """
    Converts all dictionary elements to string type - similar to what ConfigObj will
    be doing when it saves and loads the data.
    """
    if isinstance(data, collections.Mapping):
        return dict(map(convert_to_str, data.iteritems()))
    elif isinstance(data, collections.Iterable) and not isinstance(data, basestring):
        return type(data)(map(convert_to_str, data))
    else:
        return str(data)
def software.chipwhisperer.common.utils.util.copyFile (source, destination, keepOriginals = True)
def copyFile(source, destination, keepOriginals = True):
    if keepOriginals:
        shutil.copy2(source, destination)
    else:
        shutil.move(source, destination)
def software.chipwhisperer.common.utils.util.getPyFiles (dir)
def getPyFiles(dir):
    scriptList = []
    if os.path.isdir(dir):
        for fn in os.listdir(dir):
            fnfull = dir + '/' + fn
            if os.path.isfile(fnfull) and fnfull.lower().endswith('.py') and (not fnfull.endswith('
      __init__.py')) and (not fn.startswith('_')):
                scriptList.append(os.path.splitext(fn)[0])
    return scriptList
def software.chipwhisperer.common.utils.util.getRootDir ()
def getRootDir():
    path = os.path.join(os.path.dirname(__file__), "../../../")
    return os.path.normpath(path)
def software.chipwhisperer.common.utils.util.hexstr2list (data)
Convert a string with hex numbers into a list of numbers
Referenced by software.chipwhisperer.capture.targets._smartcard_gui.SmartCardGUICard.executeAPDUs(), software.chipwhisperer.common.ui.KeyScheduleDialog.KeyScheduleDialog.inTextChanged(), and software.chipwhisperer.capture.targets._smartcard_gui.APDUFilter.validateAPDU().
def hexstr2list(data):
    """Convert a string with hex numbers into a list of numbers"""
    data = str(data)
    newdata = data.lower()
    newdata = newdata.replace("0x", "")
    newdata = newdata.replace(",", "")
    newdata = newdata.replace(" ", "")
    newdata = newdata.replace("[", "")
    newdata = newdata.replace("]", "")
    newdata = newdata.replace("(", "")
    newdata = newdata.replace(")", "")
    newdata = newdata.replace("{", "")
    newdata = newdata.replace("}", "")
    newdata = newdata.replace(":", "")
    newdata = newdata.replace("-", "")
    datalist = [int(newdata[i:(i + 2)], 16) for i in range(0, len(newdata), 2)]
    return datalist
def software.chipwhisperer.common.utils.util.hexStrToByteArray (hexStr)
def hexStrToByteArray(hexStr):
    ba = bytearray()
    for s in hexStr.split():
        ba.append(int(s, 16))
    return ba
def software.chipwhisperer.common.utils.util.list2hexstr (data, delim = '', prefix = '')
Convert a list of integers to a hex string, with optional deliminators/prefix

delim is inserted between each list item

prefix is inserted infront of each item (including first item)
def list2hexstr(data, delim='', prefix=''):
    """
    Convert a list of integers to a hex string, with optional deliminators/prefix
    delim is inserted between each list item
    prefix is inserted infront of each item (including first item)
    """
    rstr = ["%02x" % t for t in data]
    rstr = (delim + prefix).join(rstr)
    rstr = prefix + rstr
    return rstr
def software.chipwhisperer.common.utils.util.setUIupdateFunction (func)
def setUIupdateFunction(func):
    global _uiupdateFunction
    _uiupdateFunction= func
def software.chipwhisperer.common.utils.util.strippedName (fullFileName)
def strippedName(fullFileName):
    (filepath, filename) = os.path.split(fullFileName)
    (base, toplevel) = os.path.split(filepath)
    return toplevel + "/" + filename
def software.chipwhisperer.common.utils.util.strListToList (strlist)
Convert string in form of '"[33, 42, 43]", "[24, 43, 4]"'
into a normal list.
def strListToList(strlist):
    """
    Convert string in form of '"[33, 42, 43]", "[24, 43, 4]"'
    into a normal list.
    """
    strlist = strlist.replace('"', '')
    strlist = strlist.replace("'", "")
    try:
        listeval = ast.literal_eval(strlist)
        return listeval
    except ValueError:
        raise ValueError("Failed to convert %s to list" % (strlist))
def software.chipwhisperer.common.utils.util.updateUI ()
References software.chipwhisperer.common.utils.util._uiupdateFunction.
def updateUI():
    if _uiupdateFunction:
        _uiupdateFunction()
Variable Documentation
software.chipwhisperer.common.utils.util._uiupdateFunction = None
Referenced by software.chipwhisperer.common.utils.util.updateUI().
software.chipwhisperer.common.utils.util.DictType = OrderedDict