software.chipwhisperer.capture.targets.smartcard_readers._base.ReaderTemplate Class Reference
Public Member Functions
def __init__
def setSomething (self)
def sendAPDU
def con
def close (self)
def flush (self)
def reset (self)
def getATR (self)
Constructor & Destructor Documentation
def software.chipwhisperer.capture.targets.smartcard_readers._base.ReaderTemplate.__init__ (self, parentParam = None)
    def __init__(self, parentParam=None):
        Parameterized.__init__(self, parentParam)
        # self.params.addChildren([
        # {'name':'Example Parameter', 'type':'int', 'value':5, 'set':self.setSomething}
        # ])
Member Function Documentation
def software.chipwhisperer.capture.targets.smartcard_readers._base.ReaderTemplate.close (self)
Close connection.
Referenced by software.chipwhisperer.common.traces.TraceContainerDPAv3.ImportDPAv3Dialog.doImport(), and software.chipwhisperer.common.ui.CWMainGUI.CWMainGUI.exceptionHandlerDialog().
    def close(self):
        """Close connection."""
        pass
def software.chipwhisperer.capture.targets.smartcard_readers._base.ReaderTemplate.con (self, scope = None)
Connect to reader.
Referenced by software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.listAllTables(), software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.prepareDisk(), and software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.updateConfigData().
    def con(self, scope=None):
        """Connect to reader."""
        pass
def software.chipwhisperer.capture.targets.smartcard_readers._base.ReaderTemplate.flush (self)
Discard all input buffers
Referenced by software.chipwhisperer.hardware.naeusb.bootloader_sam3u.Samba.flush(), and software.chipwhisperer.hardware.naeusb.bootloader_sam3u.Samba.go().
    def flush(self):
        """Discard all input buffers"""
        pass
def software.chipwhisperer.capture.targets.smartcard_readers._base.ReaderTemplate.getATR (self)
Get the ATR from the SmartCard. Reads a saved value, user reset() to actually reset card.
    def getATR(self):
        """Get the ATR from the SmartCard. Reads a saved value, user reset() to actually reset card."""
        pass
def software.chipwhisperer.capture.targets.smartcard_readers._base.ReaderTemplate.reset (self)
Reset card & save the ATR
Referenced by software.chipwhisperer.capture.targets.smartcard_readers.chipwhisperer_scard.ReaderChipWhispererSCard.__init__(), software.chipwhisperer.capture.targets.smartcard_readers.chipwhisperer_scard.ReaderChipWhispererSCard.con(), and software.chipwhisperer.capture.targets.smartcard_readers.system_ser.ReaderSystemSER.con().
    def reset(self):
        """Reset card & save the ATR"""
        pass
def software.chipwhisperer.capture.targets.smartcard_readers._base.ReaderTemplate.sendAPDU (self, cla, ins, p1, p2, txdata = None, rxdatalen = 0)
Send APDU to SmartCard, get Response
    def sendAPDU(self, cla, ins, p1, p2, txdata=None, rxdatalen=0):
        """Send APDU to SmartCard, get Response"""
        pass
def software.chipwhisperer.capture.targets.smartcard_readers._base.ReaderTemplate.setSomething (self)
Here you would send value to the reader hardware
    def setSomething(self):
        """Here you would send value to the reader hardware"""
        pass
The documentation for this class was generated from the following file:
capture/targets/smartcard_readers/_base.py