software.chipwhisperer.analyzer.utils.Partition.Partition Class Reference
Public Member Functions
def __init__ (self, parent)
def setPartMethod (self, method)
def init (self)
def createBlankTable (self, t)
def loadPartitions (self, tRange=(0,-1)
def getPartitionData (self)
def generatePartitions (self, partitionClass=None, saveFile=False, loadFile=False, tRange=(0,-1)
def setTraceSource (self, traces)
Public Attributes
partDataCache
partMethodClass
partMethod
Static Public Attributes
dictionary attrDictPartition
list supportedMethods = [PartitionRandvsFixed, PartitionEncKey, PartitionRandDebug, PartitionHWIntermediate, PartitionHDLastRound]
Detailed Description
Base Class for all partioning modules
Constructor & Destructor Documentation
def software.chipwhisperer.analyzer.utils.Partition.Partition.__init__ (self, parent)
References software.chipwhisperer.analyzer.utils.Partition.Partition.setPartMethod().
    def __init__(self, parent):
        QObject.__init__(self, parent)
        Parameterized.__init__(self)
        self.setPartMethod(PartitionRandvsFixed)
        self.partDataCache = None
Member Function Documentation
def software.chipwhisperer.analyzer.utils.Partition.Partition.createBlankTable (self, t)
Referenced by software.chipwhisperer.analyzer.utils.Partition.Partition.generatePartitions(), and software.chipwhisperer.analyzer.utils.Partition.Partition.loadPartitions().
    def createBlankTable(self, t):
        # Create storage for partition information
        partitionTable = []
        #for j in range(0, len(t.getKnownKey())):
        for j in range(0, len(self.partMethod.getPartitionNum(t, 0))):
            partitionTable.append([])
            for i in range(0, self.partMethod.getNumPartitions()):
                partitionTable[j].append([])
        return partitionTable
def software.chipwhisperer.analyzer.utils.Partition.Partition.generatePartitions (self, partitionClass = None, saveFile = False, loadFile = False, tRange = (0, -1)
Generate partitions, using previously setup setTraceManager & partition class, or if they are passed as
arguments will update the class data
References software.chipwhisperer.analyzer.utils.Partition.Partition.attrDictPartition, software.chipwhisperer.analyzer.utils.Partition.Partition.createBlankTable(), software.chipwhisperer.analyzer.utils.Partition.Partition.loadPartitions(), software.chipwhisperer.analyzer.utils.Partition.Partition.partDataCache, and software.chipwhisperer.analyzer.utils.Partition.Partition.setPartMethod().
    def generatePartitions(self, partitionClass=None, saveFile=False, loadFile=False,
      tRange=(0, -1)):
        """
        Generate partitions, using previously setup setTraceManager & partition class, or if they are
       passed as
        arguments will update the class data
        """
        if partitionClass:
            self.setPartMethod(partitionClass)
        partitionTable = None
        if loadFile:
            partitionTable = self.loadPartitions(tRange)
            raise AttributeError("WARNING: loadPartitions broken for split files, disabled for now")
        start = tRange[0]
        end = tRange[1]
        if partitionTable is None:
            partitionTable = self.createBlankTable(self._traces.findMappedTrace(start))
            if end == -1:
                end = self._traces.numTraces()
            tnum = start
            while tnum < end:
                t = self._traces.findMappedTrace(tnum)
                # Discover where this trace starts & ends
                tmapstart = t.mappedRange[0]
                tmapend = t.mappedRange[1]
                
                partitionTableTemp = self.createBlankTable(self._traces.findMappedTrace(
      start))
                for tnum in range(tmapstart, tmapend + 1):
                    # Check each trace, write partition number
                    partNum = self.partMethod.getPartitionNum(t, tnum - tmapstart)
                    for i, pn in enumerate(partNum):
                        partitionTable[i][pn].append(tnum)
                        partitionTableTemp[i][pn].append(tnum - tmapstart)
                    # self.traceDone.emit(tnum)
                if saveFile:
                    # Save partition table, reference it in config file
                    newCfgDict = copy.deepcopy(self.attrDictPartition)
                    updatedDict = t.addAuxDataConfig(newCfgDict)
                    t.saveAuxData(partitionTableTemp, updatedDict)
                # Debug - Dump Table
                # for t in range(0, self.partMethod.getNumPartitions()):
                # print "Traces in %d:" % t
                # print " ",
                # print partitionTable[0][t]
                tnum = tmapend + 1
        self.partDataCache = partitionTable
        return partitionTable
def software.chipwhisperer.analyzer.utils.Partition.Partition.getPartitionData (self)
References software.chipwhisperer.analyzer.utils.Partition.Partition.partDataCache.
    def getPartitionData(self):
        return self.partDataCache
def software.chipwhisperer.analyzer.utils.Partition.Partition.init (self)
Do any initilization required once all traces are loaded
Referenced by software.chipwhisperer.capture.targets.SAKURAG.SakuraG.con(), and software.chipwhisperer.capture.targets.SASEBOGII.SaseboGII.reinit().
    def init(self):
        """Do any initilization required once all traces are loaded"""
        pass
def software.chipwhisperer.analyzer.utils.Partition.Partition.loadPartitions (self, tRange = (0, -1)
Load partitions from trace files, convert to mapped range
References software.chipwhisperer.analyzer.utils.Partition.Partition.attrDictPartition, and software.chipwhisperer.analyzer.utils.Partition.Partition.createBlankTable().
Referenced by software.chipwhisperer.analyzer.utils.Partition.Partition.generatePartitions().
    def loadPartitions(self, tRange=(0, -1)):
        """Load partitions from trace files, convert to mapped range"""
        start = tRange[0]
        end = tRange[1]
        if end == -1:
            end = self._traces.numTraces()
        # Generate blank partition table
        partitionTable = self.createBlankTable(self._traces.findMappedTrace(start))
        print np.shape(partitionTable)
        tnum = start
        while tnum < end:
            t = self._traces.findMappedTrace(tnum)
            # Discover where this trace starts & ends
            tmapstart = t.mappedRange[0]
            tmapend = t.mappedRange[1]
            tmapend = min(tmapend, end)
            partcfg = t.getAuxDataConfig(self.attrDictPartition)
            # print partcfg
            # print partcfg["filename"]
            partdata = t.loadAuxData(partcfg["filename"])
            # Merge tables now - better way to do this?
            for j in range(0, len(self.partMethod.getPartitionNum(t, 0))):
                for i in range(0, self.partMethod.getNumPartitions()):
                    partitionTable[j][i] = partitionTable[j][i] + partdata[j][i]
            # print tmapstart
            # Next trace round
            tnum = tmapend + 1
        return partitionTable
def software.chipwhisperer.analyzer.utils.Partition.Partition.setPartMethod (self, method)
Referenced by software.chipwhisperer.analyzer.utils.Partition.Partition.__init__(), and software.chipwhisperer.analyzer.utils.Partition.Partition.generatePartitions().
    def setPartMethod(self, method):
        self.partMethodClass = method
        self.partMethod = method()
        self.attrDictPartition["sectionName"] = self.partMethod.sectionName
        self.attrDictPartition["moduleName"] = self.partMethod.__class__.__name__
def software.chipwhisperer.analyzer.utils.Partition.Partition.setTraceSource (self, traces)
References software.chipwhisperer.analyzer.utils.Partition.Partition._traces.
    def setTraceSource(self, traces):
        self._traces = traces
Member Data Documentation
dictionary software.chipwhisperer.analyzer.utils.Partition.Partition.attrDictPartition [static]
Initial value:
= {
                "sectionName":"Partition Based on XXXX",
                "moduleName":"Partitions",
                "module":None,
                "values":{
                    "round":{"value":0, "desc":"Round", "changed":False, "definesunique":True},
                    "filename":{"value":None, "desc":"Partition File", "changed":False, "headerLabel":"
      Partition Data"},
                    },
                }
Referenced by software.chipwhisperer.analyzer.utils.Partition.Partition.generatePartitions(), and software.chipwhisperer.analyzer.utils.Partition.Partition.loadPartitions().
software.chipwhisperer.analyzer.utils.Partition.Partition.partDataCache
Referenced by software.chipwhisperer.analyzer.utils.Partition.Partition.generatePartitions(), and software.chipwhisperer.analyzer.utils.Partition.Partition.getPartitionData().
software.chipwhisperer.analyzer.utils.Partition.Partition.partMethod
software.chipwhisperer.analyzer.utils.Partition.Partition.partMethodClass
list software.chipwhisperer.analyzer.utils.Partition.Partition.supportedMethods = [PartitionRandvsFixed, PartitionEncKey, PartitionRandDebug, PartitionHWIntermediate, PartitionHDLastRound] [static]
Referenced by software.chipwhisperer.analyzer.utils.TraceExplorerScripts.PartitionDisplay.DifferenceMode.__init__().
The documentation for this class was generated from the following file:
Partition.py