software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC Class Reference
Public Member Functions
def __init__
def setKeepalive (self, kinterval)
def timeoutFired (self)
def sendAPDU
def con
def flush (self)
def reset (self)
def getATR (self)
def dis (self)
Public Attributes
timeoutTimer
sccard
screq
scserv
Constructor & Destructor Documentation
def software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.__init__ (self, parentParam = None)
    def __init__(self, parentParam=None):
        ReaderTemplate.__init__(self, parentParam)
        self.timeoutTimer = timer.Timer()
        self.timeoutTimer.timeout.connect(self.timeoutFired)
        self.timeoutTimer.setInterval(2000)
        self.params.addChildren([
            {'name':'Keep-Alive Interval (off=0)', 'type':'int', 'value':2, 'set':self.
      setKeepalive}
        ])
Member Function Documentation
def software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.con (self, scope = None)
Connect to reader. scope parameter is OpenADC/ChipWhisperer hardware, only used to integrated readers
Referenced by software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.listAllTables(), software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.prepareDisk(), and software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.updateConfigData().
    def con(self, scope = None):
        """Connect to reader. scope parameter is OpenADC/ChipWhisperer hardware, only used to integrated
       readers"""
        try:
            self.sccard = AnyCardType()
            self.screq = CardRequest(timeout=1, cardType=self.sccard)
            self.scserv = self.screq.waitforcard()
            if not self.timeoutTimer.isActive():
                self.timeoutTimer.start()
            print "SCARD: Connected..."
        except Exception:
            raise Exception("SCARD: Failed to connect...")
def software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.dis (self)
Referenced by software.chipwhisperer.capture.scopes.VisaScope.VisaScopeInterface.arm(), software.chipwhisperer.capture.scopes.OpenADC.OpenADCInterface.arm(), software.chipwhisperer.capture.scopes.PicoScope.PicoScopeInterface.arm(), software.chipwhisperer.capture.targets.simpleserial_readers.cwlite.SimpleSerial_ChipWhispererLite.con(), software.chipwhisperer.capture.scopes.OpenADC.OpenADCInterface.dcmTimeout(), software.chipwhisperer.capture.targets.SimpleSerial.SimpleSerial.runCommand(), and software.chipwhisperer.capture.targets.SASEBOGII.SaseboGII.write().
    def dis(self):
        self.scserv.connection.disconnect()
        self.timeoutTimer.stop()
def software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.flush (self)
Discard all input buffers
Referenced by software.chipwhisperer.hardware.naeusb.bootloader_sam3u.Samba.flush(), and software.chipwhisperer.hardware.naeusb.bootloader_sam3u.Samba.go().
    def flush(self):
        """Discard all input buffers"""
        pass
def software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.getATR (self)
Get the ATR from the SmartCard. Reads a saved value, user reset() to actually reset card.
    def getATR(self):
        """Get the ATR from the SmartCard. Reads a saved value, user reset() to actually reset card."""
        pass
def software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.reset (self)
Reset card & save the ATR
Referenced by software.chipwhisperer.capture.targets.smartcard_readers.system_ser.ReaderSystemSER.con().
    def reset(self):
        """Reset card & save the ATR"""
        pass
def software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.sendAPDU (self, cla, ins, p1, p2, txdata = None, rxdatalen = 0)
Send APDU to SmartCard, get Response
    def sendAPDU(self, cla, ins, p1, p2, txdata=None, rxdatalen=0):
        """Send APDU to SmartCard, get Response"""
        data = [cla,ins, p1, p2]
        if txdata is not None:
            txdatalen = len(txdata)
            data.append(txdatalen)
        else:
            txdatalen = 0
        if (txdata is None) & (rxdatalen == 0):
            data.append(0)
        #Append payload
        if txdata is not None:
            for b in txdata: data.append(b)
        if rxdatalen != 0:
            data.append(rxdatalen)
        response, sw1, sw2 = self.scserv.connection.transmit(data , CardConnection.T0_protocol)
        status = (sw1 << 8) | sw2
        if rxdatalen > 0:
            return (status, response)
        return status
def software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.setKeepalive (self, kinterval)
    def setKeepalive(self, kinterval):
        self.timeoutTimer.setInterval(kinterval*1000)
def software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.timeoutFired (self)
    def timeoutFired(self):
        self.scserv.connection.connect()
Member Data Documentation
software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.sccard
software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.screq
software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.scserv
software.chipwhisperer.capture.targets.smartcard_readers.pcsc.ReaderPCSC.timeoutTimer
The documentation for this class was generated from the following file:
pcsc.py