software.chipwhisperer.analyzer.attacks._channel_estimate_attack.ChannelEstimateAttackOneSubkey Class Reference
Public Member Functions
def __init__ (self)
def clearStats (self)
def oneSubkey
Detailed Description
Redos entire attack 
Constructor & Destructor Documentation
def software.chipwhisperer.analyzer.attacks._channel_estimate_attack.ChannelEstimateAttackOneSubkey.__init__ (self)
References software.chipwhisperer.analyzer.attacks._channel_estimate_attack.ChannelEstimateAttackOneSubkey.clearStats().
    def __init__(self):
        self.clearStats()
        
Member Function Documentation
def software.chipwhisperer.analyzer.attacks._channel_estimate_attack.ChannelEstimateAttackOneSubkey.clearStats (self)
Referenced by software.chipwhisperer.analyzer.attacks._channel_estimate_attack.ChannelEstimateAttackOneSubkey.__init__(), software.chipwhisperer.analyzer.attacks.cpa_algorithms.progressive.CPAProgressiveOneSubkey.__init__(), software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.CPAProgressiveOneSubkey.__init__(), software.chipwhisperer.analyzer.attacks.cpa_algorithms.progressive_caccel.CPAProgressiveOneSubkey.__init__(), software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.MinDistOneSubkey.__init__(), and software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateOneSubkey.__init__().
    def clearStats(self):
        pass
    
def software.chipwhisperer.analyzer.attacks._channel_estimate_attack.ChannelEstimateAttackOneSubkey.oneSubkey (self, bnum, traces_fit, traces_test, plaintexts_fit, plaintexts_test, model, modeltype = `Hamming Weight`, key = None, printData = False, aroundStartEnd = False, useSVD = True, tracefitPInv = False, progressBar = None, pbcnt = 0)
                  progressBar=None, pbcnt=0):
        if tracefitPInv:
            ntracesfit = len(traces_fit[0,:])
        else:
            ntracesfit = len(traces_fit[:,0])
        ntracestry = len(traces_test[:,0])
        if printData:
            print " Key %d = %2x"%(bnum, key[bnum])
        start = 0
        end = 256
        if aroundStartEnd:
            start = key[bnum] - 5
            end = key[bnum] + 6
        if start < 0:
            start = 0
        
        if end > 256:
            end = 256
        result = []
        diffs = [1E99]*256
        for guess in range(start, end):
            if printData:
                print " %2x "%guess,
                
            hwlst = np.zeros((ntracesfit, 1))
            for i,t in enumerate(plaintexts_fit):
                hwlst[i][0] = AES128_8bit.HypHW(t, None, guess, bnum)
    
            if useSVD:
                if tracefitPInv:
                    #traces_fit already a pseudoinverse
                    channel = np.dot(traces_fit, hwlst)
                else:
                    #Use pseudo-inverse which is fairly fast, as NumPY uses a SVD decomposition
                    channel = np.dot(np.linalg.pinv(traces_fit), hwlst)
            else:
                #Classic but VERY SLOW least-squares
                channel = np.linalg.lstsq(traces_fit, hwlst)[0]
            hwtry = np.zeros((ntracestry, 1))
            for i,t in enumerate(plaintexts_test):
                hwtry[i][0] = AES128_8bit.HypHW(t, None, guess, bnum)
            res = np.dot(traces_test,channel)
            res = ((res-hwtry)**2).sum()
            diffs[guess] = res
            if printData:
                print "%E"%res
                result.append({'sse':res, 'guess':guess, 'csi':channel})
    
        if printData:
            sortedresult = sorted(result, key=itemgetter('sse'))
            print "answer @ rank %d"%map(itemgetter('guess'), sortedresult).index(key[bnum])
        return (diffs, pbcnt)
#Hacks for main()
sys.path.append('../../common')
sys.path.append('../.')
The documentation for this class was generated from the following file:
_channel_estimate_attack.py