software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate Class Reference
Public Member Functions
def __init__
def __del__ (self)
def close (self)
def captureInit (self)
def captureComplete (self)
def traceArm (self)
def traceArmPost (self)
def traceDone (self)
def setPrefix (self, prefix)
Public Attributes
prefix
Constructor & Destructor Documentation
def software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.__init__ (self, parentParam = None)
    def __init__(self, parentParam=None):
        Parameterized.__init__(self, parentParam)
        self.prefix = ""
def software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.__del__ (self)
Close system if needed
References software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.close().
    def __del__(self):
        """Close system if needed"""
        print "Aux: Closing"
        self.close()
Member Function Documentation
def software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.captureComplete (self)
Called once complete api is complete
    def captureComplete(self):
        """Called once complete api is complete"""
        pass
def software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.captureInit (self)
Called once before each api grouping, do connect etc
    def captureInit(self):
        """Called once before each api grouping, do connect etc"""
        pass
def software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.close (self)
Close target, disconnect if required
Referenced by software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.__del__(), software.chipwhisperer.capture.targets.SmartCard.SmartCard.__del__(), software.chipwhisperer.capture.scopes._qt.OpenADCQt.__del__(), software.chipwhisperer.capture.scopes.cwhardware.ChipWhispererTargets.CWSCardIntegrated.__del__(), software.chipwhisperer.capture.targets.simpleserial_readers._base.SimpleSerialTemplate.dis(), software.chipwhisperer.capture.targets._base.TargetTemplate.dis(), software.chipwhisperer.common.traces.TraceContainerDPAv3.ImportDPAv3Dialog.doImport(), and software.chipwhisperer.common.ui.CWMainGUI.CWMainGUI.exceptionHandlerDialog().
    def close(self):
        """Close target, disconnect if required"""
        pass
def software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.setPrefix (self, prefix)
    def setPrefix(self, prefix):
        self.prefix = prefix
def software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.traceArm (self)
Called before arming scope, use to arm aux system
    def traceArm(self):
        """Called before arming scope, use to arm aux system"""
        pass
def software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.traceArmPost (self)
Called after arming scope, before sending trigger to target
    def traceArmPost(self):
        """Called after arming scope, before sending trigger to target"""
        pass
def software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.traceDone (self)
Called once api is complete for a single trace
    def traceDone(self):
        """Called once api is complete for a single trace"""
        pass
Member Data Documentation
software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.prefix
Referenced by software.chipwhisperer.capture.auxiliary.FrequencyMeasure.FrequencyMeasure.captureComplete(), and software.chipwhisperer.capture.auxiliary._base.AuxiliaryTemplate.setPrefix().
The documentation for this class was generated from the following file:
capture/auxiliary/_base.py