var namespacesoftware_1_1chipwhisperer_1_1capture_1_1scopes_1_1cwhardware_1_1ChipWhispererTargets =
[
    [ "CWSCardIntegrated", "d0/db2/classsoftware_1_1chipwhisperer_1_1capture_1_1scopes_1_1cwhardware_1_1ChipWhispererTargets_1_1CWSCardIntegrated.html", "d0/db2/classsoftware_1_1chipwhisperer_1_1capture_1_1scopes_1_1cwhardware_1_1ChipWhispererTargets_1_1CWSCardIntegrated" ],
    [ "CWUniversalSerial", "d9/d6a/classsoftware_1_1chipwhisperer_1_1capture_1_1scopes_1_1cwhardware_1_1ChipWhispererTargets_1_1CWUniversalSerial.html", "d9/d6a/classsoftware_1_1chipwhisperer_1_1capture_1_1scopes_1_1cwhardware_1_1ChipWhispererTargets_1_1CWUniversalSerial" ],
    [ "CWUniversalSerialProcessor", "d4/da5/classsoftware_1_1chipwhisperer_1_1capture_1_1scopes_1_1cwhardware_1_1ChipWhispererTargets_1_1CWUniversalSerialProcessor.html", "d4/da5/classsoftware_1_1chipwhisperer_1_1capture_1_1scopes_1_1cwhardware_1_1ChipWhispererTargets_1_1CWUniversalSerialProcessor" ]
];