software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit Class Reference
Public Member Functions
def __init__
def __getitem__ (self, addr16)
def __setitem__ (self, addr16, word)
def minaddr (self)
def maxaddr (self)
def tobinarray
Public Attributes
padding
start_addr
Additional Inherited Members
Detailed Description
Access to data as 16-bit words. Intended to use with Microchip HEX files.
Constructor & Destructor Documentation
def software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.__init__ (self, source = None)
Construct class from HEX file
or from instance of ordinary IntelHex class. If IntelHex object
is passed as source, the original IntelHex object should not be used
again because this class will alter it. This class leaves padding
alone unless it was precisely 0xFF. In that instance it is sign
extended to 0xFFFF.

@param  source  file name of HEX file or file object
        or instance of ordinary IntelHex class.
        Will also accept dictionary from todict method.
    def __init__(self, source=None):
        """Construct class from HEX file
        or from instance of ordinary IntelHex class. If IntelHex object
        is passed as source, the original IntelHex object should not be used
        again because this class will alter it. This class leaves padding
        alone unless it was precisely 0xFF. In that instance it is sign
        extended to 0xFFFF.
        @param source file name of HEX file or file object
                        or instance of ordinary IntelHex class.
                        Will also accept dictionary from todict method.
        """
        if isinstance(source, IntelHex):
            # from ihex8
            self.padding = source.padding
            self.start_addr = source.start_addr
            # private members
            self._buf = source._buf
            self._offset = source._offset
        elif isinstance(source, dict):
            raise IntelHexError("IntelHex16bit does not support initialization from dictionary
       yet.\n"
                                "Patches are welcome.")
        else:
            IntelHex.__init__(self, source)
        if self.padding == 0x0FF:
            self.padding = 0x0FFFF
Member Function Documentation
def software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.__getitem__ (self, addr16)
Get 16-bit word from address.
Raise error if only one byte from the pair is set.
We assume a Little Endian interpretation of the hex file.

@param  addr16  address of word (addr8 = 2 * addr16).
@return         word if bytes exists in HEX file, or self.padding
        if no data found.
References software.chipwhisperer.capture.utils.IntelHex.IntelHex.padding.
    def __getitem__(self, addr16):
        """Get 16-bit word from address.
        Raise error if only one byte from the pair is set.
        We assume a Little Endian interpretation of the hex file.
        @param addr16 address of word (addr8 = 2 * addr16).
        @return word if bytes exists in HEX file, or self.padding
                        if no data found.
        """
        addr1 = addr16 * 2
        addr2 = addr1 + 1
        byte1 = self._buf.get(addr1, None)
        byte2 = self._buf.get(addr2, None)
        if byte1 != None and byte2 != None:
            return byte1 | (byte2 << 8) # low endian
        if byte1 == None and byte2 == None:
            return self.padding
        raise BadAccess16bit(address=addr16)
def software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.__setitem__ (self, addr16, word)
Sets the address at addr16 to word assuming Little Endian mode.
References software.chipwhisperer.capture.utils.IntelHex.IntelHex._buf.
    def __setitem__(self, addr16, word):
        """Sets the address at addr16 to word assuming Little Endian mode.
        """
        addr_byte = addr16 * 2
        b = divmod(word, 256)
        self._buf[addr_byte] = b[1]
        self._buf[addr_byte + 1] = b[0]
def software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.maxaddr (self)
Get maximal address of HEX content in 16-bit mode.

@return         maximal address used in this object 
References software.chipwhisperer.capture.utils.IntelHex.IntelHex._buf, and software.chipwhisperer.capture.utils.IntelHex.dict_keys().
    def maxaddr(self):
        '''Get maximal address of HEX content in 16-bit mode.
        @return maximal address used in this object
        '''
        aa = dict_keys(self._buf)
        if aa == []:
            return 0
        else:
            return max(aa) >> 1
def software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.minaddr (self)
Get minimal address of HEX content in 16-bit mode.

@return         minimal address used in this object
References software.chipwhisperer.capture.utils.IntelHex.IntelHex._buf, and software.chipwhisperer.capture.utils.IntelHex.dict_keys().
    def minaddr(self):
        '''Get minimal address of HEX content in 16-bit mode.
        @return minimal address used in this object
        '''
        aa = dict_keys(self._buf)
        if aa == []:
            return 0
        else:
            return min(aa) >> 1
def software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.tobinarray (self, start = None, end = None, size = None)
Convert this object to binary form as array (of 2-bytes word data).
If start and end unspecified, they will be inferred from the data.
@param  start   start address of output data.
@param  end     end address of output data (inclusive).
@param  size    size of the block (number of words),
        used with start or end parameter.
@return         array of unsigned short (uint16_t) data.
References software.chipwhisperer.capture.utils.IntelHex.IntelHex._buf, software.chipwhisperer.capture.utils.IntelHex.IntelHex._get_start_end(), and software.chipwhisperer.capture.utils.IntelHex.range_g.
    def tobinarray(self, start=None, end=None, size=None):
        '''Convert this object to binary form as array (of 2-bytes word data).
        If start and end unspecified, they will be inferred from the data.
        @param start start address of output data.
        @param end end address of output data (inclusive).
        @param size size of the block (number of words),
                        used with start or end parameter.
        @return array of unsigned short (uint16_t) data.
        '''
        bin = array('H')
        if self._buf == {} and None in (start, end):
            return bin
        if size is not None and size <= 0:
            raise ValueError("tobinarray: wrong value for size")
        start, end = self._get_start_end(start, end, size)
        for addr in range_g(start, end + 1):
            bin.append(self[addr])
        return bin
# /class IntelHex16bit
Member Data Documentation
software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.padding
software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.start_addr
The documentation for this class was generated from the following file:
IntelHex.py