software.chipwhisperer.capture.scopes._base.ScopeTemplate Class Reference
Public Member Functions
def __init__ (self, parentParam)
def dcmTimeout (self)
def setAutorefreshDCM (self, enabled)
def setCurrentScope
def getStatus (self)
def con (self)
def dis (self)
def doDataUpdated
def arm (self)
def capture
Public Attributes
connectStatus
dataUpdated
datapoints
Constructor & Destructor Documentation
def software.chipwhisperer.capture.scopes._base.ScopeTemplate.__init__ (self, parentParam)
    def __init__(self, parentParam):
        Parameterized.__init__(self, parentParam)
        self.connectStatus = util.Observable(False)
        self.dataUpdated = util.Signal()
        self.datapoints = []
Member Function Documentation
def software.chipwhisperer.capture.scopes._base.ScopeTemplate.arm (self)
    def arm(self):
        pass
        #NOTE - if reimplementing this, should always check for connection first
        #if self.connectStatus.value() is False:
        # raise Exception("Scope \"" + self.getName() + "\" is not connected. Connect it first...")
        #raise NotImplementedError("Scope \"" + self.getName() + "\" does not implement method " +
       self.__class__.__name__ + ".arm()")
def software.chipwhisperer.capture.scopes._base.ScopeTemplate.capture (self, update = True, NumberPoints = None)
    def capture(self, update=True, NumberPoints=None):
        #NOTE: If you have a waiting loop (waiting for arm), call the function util.updateUI() inside that
       loop to keep
        # the UI responsive:
        #
        # while self.done() == False:
        # time.sleep(0.05)
        # util.updateUI()
        
        pass
def software.chipwhisperer.capture.scopes._base.ScopeTemplate.con (self)
References software.chipwhisperer.capture.scopes._base.ScopeTemplate._con(), and software.chipwhisperer.common.utils.parameters.Parameterized.getName().
Referenced by software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.listAllTables(), software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.prepareDisk(), and software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.updateConfigData().
    def con(self):
        LiveTraceSource(self, self.getName() + " - Channel 1").register()
        if self._con():
            self.connectStatus.setValue(True)
def software.chipwhisperer.capture.scopes._base.ScopeTemplate.dcmTimeout (self)
    def dcmTimeout(self):
        pass
def software.chipwhisperer.capture.scopes._base.ScopeTemplate.dis (self)
References software.chipwhisperer.capture.scopes._base.ScopeTemplate._dis(), and software.chipwhisperer.common.utils.parameters.Parameterized.getName().
Referenced by software.chipwhisperer.capture.scopes.VisaScope.VisaScopeInterface.arm(), software.chipwhisperer.capture.scopes.OpenADC.OpenADCInterface.arm(), software.chipwhisperer.capture.scopes.PicoScope.PicoScopeInterface.arm(), software.chipwhisperer.capture.scopes.OpenADC.OpenADCInterface.dcmTimeout(), software.chipwhisperer.capture.targets.SimpleSerial.SimpleSerial.runCommand(), and software.chipwhisperer.capture.targets.SASEBOGII.SaseboGII.write().
    def dis(self):
        if self._dis():
            TraceSource.deregister(self.getName() + " - Channel 1")
            self.connectStatus.setValue(False)
def software.chipwhisperer.capture.scopes._base.ScopeTemplate.doDataUpdated (self, l, offset = 0)
    def doDataUpdated(self, l, offset=0):
        self.dataUpdated.emit(l, offset)
def software.chipwhisperer.capture.scopes._base.ScopeTemplate.getStatus (self)
Referenced by software.chipwhisperer.capture.scopes._OpenADCInterface.OpenADCInterface.capture(), and software.chipwhisperer.capture.scopes._OpenADCInterface.OpenADCInterface.devicePresent().
    def getStatus(self):
        return self.connectStatus.value()
def software.chipwhisperer.capture.scopes._base.ScopeTemplate.setAutorefreshDCM (self, enabled)
    def setAutorefreshDCM(self, enabled):
        pass
def software.chipwhisperer.capture.scopes._base.ScopeTemplate.setCurrentScope (self, scope, update = True)
Referenced by software.chipwhisperer.capture.scopes.VisaScope.VisaScopeInterface.__init__(), and software.chipwhisperer.capture.scopes.PicoScope.PicoScopeInterface.__init__().
    def setCurrentScope(self, scope, update=True):
        pass
Member Data Documentation
software.chipwhisperer.capture.scopes._base.ScopeTemplate.connectStatus
software.chipwhisperer.capture.scopes._base.ScopeTemplate.datapoints
Referenced by software.chipwhisperer.capture.scopes.visascope_interface._base.VisaScope.capture(), software.chipwhisperer.capture.scopes.PicoScope.PicoScopeInterface.doDataUpdated(), and software.chipwhisperer.capture.scopes._qt.OpenADCQt.read().
software.chipwhisperer.capture.scopes._base.ScopeTemplate.dataUpdated
The documentation for this class was generated from the following file:
capture/scopes/_base.py