software.chipwhisperer.capture.auxiliary.ResetAVR.ResetAVR Class Reference
Public Member Functions
def __init__
def captureInit (self)
def captureComplete (self)
def traceArm (self)
def traceDone (self)
def testReset (self)
Constructor & Destructor Documentation
def software.chipwhisperer.capture.auxiliary.ResetAVR.ResetAVR.__init__ (self, parentParam = None)
References software.chipwhisperer.capture.auxiliary.ResetAVR.ResetAVR.testReset().
    def __init__(self, parentParam=None):
        AuxiliaryTemplate.__init__(self, parentParam)
        self.params.addChildren([
            {'name':'STK500.exe Path', 'type':'str', 'key':'stk500path', 'value':r'C:\Program Files (x86)\A
      tmel\AVR Tools\STK500\Stk500.exe'},
            {'name':'AVR Part', 'type':'list', 'key':'part', 'values':['atmega328p'], 'value':'atmega328p'}
      ,
            {'name':'Test Reset', 'type':'action', 'action':self.testReset}
        ])
Member Function Documentation
def software.chipwhisperer.capture.auxiliary.ResetAVR.ResetAVR.captureComplete (self)
    def captureComplete(self):
        pass
def software.chipwhisperer.capture.auxiliary.ResetAVR.ResetAVR.captureInit (self)
    def captureInit(self):
        pass
def software.chipwhisperer.capture.auxiliary.ResetAVR.ResetAVR.testReset (self)
Referenced by software.chipwhisperer.capture.auxiliary.ResetAVR.ResetAVR.__init__(), and software.chipwhisperer.capture.auxiliary.ResetCW1173Read.ResetCW1173Read.__init__().
    def testReset(self):
        self.traceArm()
def software.chipwhisperer.capture.auxiliary.ResetAVR.ResetAVR.traceArm (self)
Referenced by software.chipwhisperer.capture.auxiliary.ResetAVR.ResetAVR.testReset().
    def traceArm(self):
        # If using STK500
        stk500 = self.findParam('stk500path').value()
        ret = call([stk500, "-d%s" % self.findParam('part').value(), "-s", "-cUSB"])
        if int(ret) != 0:
            raise IOError("Error Calling Stk500.exe")
        time.sleep(1)
        # If using AVRDude
        # call(["avrdude"])
def software.chipwhisperer.capture.auxiliary.ResetAVR.ResetAVR.traceDone (self)
    def traceDone(self):
        pass
The documentation for this class was generated from the following file:
ResetAVR.py