software.chipwhisperer.analyzer.utils.Partition.PartitionHDLastRound Class Reference
Public Member Functions
def getNumPartitions (self)
def getPartitionNum (self, trace, tnum)
Static Public Attributes
string sectionName = `Partition Based on HD of Last Round`
string partitionType = `HD AES Last-Round`
Member Function Documentation
def software.chipwhisperer.analyzer.utils.Partition.PartitionHDLastRound.getNumPartitions (self)
    def getNumPartitions(self):
        return 9
def software.chipwhisperer.analyzer.utils.Partition.PartitionHDLastRound.getPartitionNum (self, trace, tnum)
References software.chipwhisperer.analyzer.attacks.models.AES128_8bit.getHW(), software.chipwhisperer.analyzer.models.aes.funcs.inv_sbox(), and software.chipwhisperer.analyzer.models.aes.key_schedule.keyScheduleRounds().
    def getPartitionNum(self, trace, tnum):
        key = trace.getKnownKey(tnum)
        ct = trace.getTextout(tnum)
        #Convert from initial key to final-round key, currently
        #this assumes AES
        if len(key) == 16:
            rounds = 10
        else:
            raise ValueError("Need to implement for selected AES")
        key = keyScheduleRounds(key, 0, rounds)
        guess = [0] * 16
        for i in range(0, 16):
            st10 = ct[INVSHIFT[i]]
            st9 = inv_sbox(ct[i] ^ key[i])
            guess[i] = getHW(st9 ^ st10)
        return guess
Member Data Documentation
string software.chipwhisperer.analyzer.utils.Partition.PartitionHDLastRound.partitionType = `HD AES Last-Round` [static]
string software.chipwhisperer.analyzer.utils.Partition.PartitionHDLastRound.sectionName = `Partition Based on HD of Last Round` [static]
The documentation for this class was generated from the following file:
Partition.py