Flowchart.FlowchartCtrlWidget Class Reference
Public Member Functions
def __init__ (self, chart)
def chartToggled (self, b)
def reloadClicked (self)
def loadClicked (self)
def fileSaved (self, fileName)
def saveClicked (self)
def saveAsClicked (self)
def setCurrentFile (self, fileName)
def itemChanged (self, args)
def scene (self)
def viewBox (self)
def nodeRenamed (self, node, oldName)
def addNode (self, node)
def removeNode (self, node)
def bypassClicked (self)
def chartWidget (self)
def outputChanged (self, data)
def clear (self)
def select (self, node)
Public Attributes
items
currentFileName
chart
ui
chartWidget
cwWin
Detailed Description
The widget that contains the list of all the nodes in a flowchart and their controls, as well as buttons for loading/saving flowcharts.
Constructor & Destructor Documentation
def Flowchart.FlowchartCtrlWidget.__init__ (self, chart)
    def __init__(self, chart):
        self.items = {}
        #self.loadDir = loadDir ## where to look initially for chart files
        self.currentFileName = None
        QtGui.QWidget.__init__(self)
        self.chart = chart
        self.ui = FlowchartCtrlTemplate.Ui_Form()
        self.ui.setupUi(self)
        self.ui.ctrlList.setColumnCount(2)
        #self.ui.ctrlList.setColumnWidth(0, 200)
        self.ui.ctrlList.setColumnWidth(1, 20)
        self.ui.ctrlList.setVerticalScrollMode(self.ui.ctrlList.ScrollPerPixel)
        self.ui.ctrlList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        
        self.chartWidget = FlowchartWidget(chart, self)
        #self.chartWidget.viewBox().autoRange()
        self.cwWin = QtGui.QMainWindow()
        self.cwWin.setWindowTitle('Flowchart')
        self.cwWin.setCentralWidget(self.chartWidget)
        self.cwWin.resize(1000,800)
        
        h = self.ui.ctrlList.header()
        h.setResizeMode(0, h.Stretch)
        
        self.ui.ctrlList.itemChanged.connect(self.itemChanged)
        self.ui.loadBtn.clicked.connect(self.loadClicked)
        self.ui.saveBtn.clicked.connect(self.saveClicked)
        self.ui.saveAsBtn.clicked.connect(self.saveAsClicked)
        self.ui.showChartBtn.toggled.connect(self.chartToggled)
        self.chart.sigFileLoaded.connect(self.setCurrentFile)
        self.ui.reloadBtn.clicked.connect(self.reloadClicked)
        self.chart.sigFileSaved.connect(self.fileSaved)
        
    
        
Member Function Documentation
def Flowchart.FlowchartCtrlWidget.addNode (self, node)
References Flowchart.FlowchartCtrlWidget.bypassClicked(), and Flowchart.FlowchartCtrlWidget.items.
    def addNode(self, node):
        ctrl = node.ctrlWidget()
        #if ctrl is None:
            #return
        item = QtGui.QTreeWidgetItem([node.name(), '', ''])
        self.ui.ctrlList.addTopLevelItem(item)
        byp = QtGui.QPushButton('X')
        byp.setCheckable(True)
        byp.setFixedWidth(20)
        item.bypassBtn = byp
        self.ui.ctrlList.setItemWidget(item, 1, byp)
        byp.node = node
        node.bypassButton = byp
        byp.setChecked(node.isBypassed())
        byp.clicked.connect(self.bypassClicked)
        
        if ctrl is not None:
            item2 = QtGui.QTreeWidgetItem()
            item.addChild(item2)
            self.ui.ctrlList.setItemWidget(item2, 0, ctrl)
            
        self.items[node] = item
        
def Flowchart.FlowchartCtrlWidget.bypassClicked (self)
Referenced by Flowchart.FlowchartCtrlWidget.addNode(), and Flowchart.FlowchartCtrlWidget.removeNode().
    def bypassClicked(self):
        btn = QtCore.QObject.sender(self)
        btn.node.bypass(btn.isChecked())
            
def Flowchart.FlowchartCtrlWidget.chartToggled (self, b)
    def chartToggled(self, b):
        if b:
            self.cwWin.show()
        else:
            self.cwWin.hide()
def Flowchart.FlowchartCtrlWidget.chartWidget (self)
References Flowchart.FlowchartCtrlWidget.chartWidget.
    def chartWidget(self):
        return self.chartWidget
def Flowchart.FlowchartCtrlWidget.clear (self)
    def clear(self):
        self.chartWidget.clear()
        
def Flowchart.FlowchartCtrlWidget.fileSaved (self, fileName)
References Flowchart.FlowchartCtrlWidget.setCurrentFile().
    def fileSaved(self, fileName):
        self.setCurrentFile(fileName)
        self.ui.saveBtn.success("Saved.")
        
def Flowchart.FlowchartCtrlWidget.itemChanged (self, args)
    def itemChanged(self, *args):
        pass
    
def Flowchart.FlowchartCtrlWidget.loadClicked (self)
    def loadClicked(self):
        newFile = self.chart.loadFile()
        #self.setCurrentFile(newFile)
        
def Flowchart.FlowchartCtrlWidget.nodeRenamed (self, node, oldName)
References Flowchart.FlowchartCtrlWidget.items.
    def nodeRenamed(self, node, oldName):
        self.items[node].setText(0, node.name())
def Flowchart.FlowchartCtrlWidget.outputChanged (self, data)
    def outputChanged(self, data):
        pass
        #self.ui.outputTree.setData(data, hideRoot=True)
def Flowchart.FlowchartCtrlWidget.reloadClicked (self)
    def reloadClicked(self):
        try:
            self.chartWidget.reloadLibrary()
            self.ui.reloadBtn.success("Reloaded.")
        except:
            self.ui.reloadBtn.success("Error.")
            raise
            
            
def Flowchart.FlowchartCtrlWidget.removeNode (self, node)
References Flowchart.FlowchartCtrlWidget.bypassClicked(), and Flowchart.FlowchartCtrlWidget.items.
    def removeNode(self, node):
        if node in self.items:
            item = self.items[node]
            #self.disconnect(item.bypassBtn, QtCore.SIGNAL('clicked()'), self.bypassClicked)
            try:
                item.bypassBtn.clicked.disconnect(self.bypassClicked)
            except TypeError:
                pass
            self.ui.ctrlList.removeTopLevelItem(item)
            
def Flowchart.FlowchartCtrlWidget.saveAsClicked (self)
References Flowchart.FlowchartCtrlWidget.currentFileName.
Referenced by Flowchart.FlowchartCtrlWidget.saveClicked().
    def saveAsClicked(self):
        try:
            if self.currentFileName is None:
                newFile = self.chart.saveFile()
            else:
                newFile = self.chart.saveFile(suggestedFileName=self.
      currentFileName)
            #self.ui.saveAsBtn.success("Saved.")
            #print "Back to saveAsClicked."
        except:
            self.ui.saveBtn.failure("Error")
            raise
            
        #self.setCurrentFile(newFile)
            
def Flowchart.FlowchartCtrlWidget.saveClicked (self)
References Flowchart.FlowchartCtrlWidget.currentFileName, and Flowchart.FlowchartCtrlWidget.saveAsClicked().
    def saveClicked(self):
        if self.currentFileName is None:
            self.saveAsClicked()
        else:
            try:
                self.chart.saveFile(self.currentFileName)
                #self.ui.saveBtn.success("Saved.")
            except:
                self.ui.saveBtn.failure("Error")
                raise
        
def Flowchart.FlowchartCtrlWidget.scene (self)
    def scene(self):
        return self.chartWidget.scene() ## returns the GraphicsScene object
    
def Flowchart.FlowchartCtrlWidget.select (self, node)
References Flowchart.FlowchartCtrlWidget.items.
    def select(self, node):
        item = self.items[node]
        self.ui.ctrlList.setCurrentItem(item)
def Flowchart.FlowchartCtrlWidget.setCurrentFile (self, fileName)
References Flowchart.FlowchartCtrlWidget.currentFileName.
Referenced by Flowchart.FlowchartCtrlWidget.fileSaved().
    def setCurrentFile(self, fileName):
        self.currentFileName = fileName
        if fileName is None:
            self.ui.fileNameLabel.setText("<b>[ new ]</b>")
        else:
            self.ui.fileNameLabel.setText("<b>%s</b>" % os.path.split(self.
      currentFileName)[1])
        self.resizeEvent(None)
def Flowchart.FlowchartCtrlWidget.viewBox (self)
Referenced by Flowchart.FlowchartWidget.nodeMenuTriggered().
    def viewBox(self):
        return self.chartWidget.viewBox()
Member Data Documentation
Flowchart.FlowchartCtrlWidget.chart
Flowchart.FlowchartCtrlWidget.chartWidget
Referenced by Flowchart.FlowchartCtrlWidget.chartWidget().
Flowchart.FlowchartCtrlWidget.currentFileName
Referenced by Flowchart.FlowchartCtrlWidget.saveAsClicked(), Flowchart.FlowchartCtrlWidget.saveClicked(), and Flowchart.FlowchartCtrlWidget.setCurrentFile().
Flowchart.FlowchartCtrlWidget.cwWin
Flowchart.FlowchartCtrlWidget.items
Referenced by Flowchart.FlowchartCtrlWidget.addNode(), Flowchart.FlowchartCtrlWidget.nodeRenamed(), Flowchart.FlowchartCtrlWidget.removeNode(), and Flowchart.FlowchartCtrlWidget.select().
Flowchart.FlowchartCtrlWidget.ui
The documentation for this class was generated from the following file:
Flowchart.py