software.chipwhisperer.common.utils.pluginmanager Namespace Reference
Classes
class Plugin
Functions
def getPluginsInDictFromPackage (path, instantiate, addNone, args, kwargs)
def importModulesInPackage (path)
def getPluginClassesFromModules (modules)
def putInDict (items, instantiate, args, kwargs)
def module_reorder (resp)
Variables
list loadedItems = []
Function Documentation
def software.chipwhisperer.common.utils.pluginmanager.getPluginClassesFromModules (modules)
Referenced by software.chipwhisperer.common.utils.pluginmanager.getPluginsInDictFromPackage().
def getPluginClassesFromModules(modules):
    resp = []
    for module in modules:
        clsmembers = inspect.getmembers(module, lambda member: inspect.isclass(member) and
      member.__module__ == module.__name__)
        for clsName, clsMember in clsmembers:
            if issubclass(clsMember, Plugin) and (not clsName.startswith('_')):
                resp.append(clsMember)
    return resp
def software.chipwhisperer.common.utils.pluginmanager.getPluginsInDictFromPackage (path, instantiate, addNone, args, kwargs)
References software.chipwhisperer.common.utils.pluginmanager.getPluginClassesFromModules(), software.chipwhisperer.common.utils.pluginmanager.importModulesInPackage(), software.chipwhisperer.common.utils.pluginmanager.module_reorder(), and software.chipwhisperer.common.utils.pluginmanager.putInDict().
Referenced by software.chipwhisperer.common.results.base.ResultsBase.getClasses().
def getPluginsInDictFromPackage(path, instantiate, addNone, *args, **kwargs):
    modules = importModulesInPackage(path)
    classes = getPluginClassesFromModules(modules)
    items = putInDict(classes, instantiate, *args, **kwargs)
    if addNone:
        items["None"] = None
    return module_reorder(items)
def software.chipwhisperer.common.utils.pluginmanager.importModulesInPackage (path)
Referenced by software.chipwhisperer.common.utils.pluginmanager.getPluginsInDictFromPackage().
def importModulesInPackage(path):
    resp = []
    for package_name in util.getPyFiles(os.path.join(util.getRootDir(), (os.path.normpath(path).replace("."
      , "/")))):# (os.path.normpath(path).replace(".", "/"))):
        full_package_name = '%s.%s' % (path, package_name)
        try:
            resp.append(importlib.import_module(full_package_name))
        except Exception as e:
            print "INFO: Could not import module: " + full_package_name + ": " + str(e)
            loadedItems.append([full_package_name, False, str(e), traceback.format_exc()])
    return resp
def software.chipwhisperer.common.utils.pluginmanager.module_reorder (resp)
Referenced by software.chipwhisperer.common.utils.pluginmanager.getPluginsInDictFromPackage().
def module_reorder(resp):
    #None is first, then alphabetical
    newresp = util.DictType()
    if 'None' in resp:
        newresp['None'] = resp['None']
        del resp['None']
    newresp.update(sorted(resp.items(), key=lambda t: t[0]))
    return newresp
def software.chipwhisperer.common.utils.pluginmanager.putInDict (items, instantiate, args, kwargs)
Referenced by software.chipwhisperer.common.utils.pluginmanager.getPluginsInDictFromPackage().
def putInDict(items, instantiate, *args, **kwargs):
    resp = util.DictType()
    for c in items:
        try:
            if instantiate:
                item = c(*args, **kwargs)
                resp[item.getName()] = item
            else:
                item = c
                resp[item.getClassName()] = item
            loadedItems.append([str(c), True, "", ""])
        except Exception as e:
            print "INFO: Could not instantiate module " + str(c) + ": " + str(e)
            loadedItems.append([str(c), False, str(e), traceback.format_exc()])
    if len(resp) == 0:
        print "Warning: Dictionary contains zero modules"
    return resp
Variable Documentation
list software.chipwhisperer.common.utils.pluginmanager.loadedItems = []