software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter Class Reference
Public Member Functions
def __init__ (self, document)
def highlightBlock (self, text)
def match_multiline (self, text, delimiter, in_state, style)
Public Attributes
tri_single
tri_double
rules
Static Public Attributes
list keywords
list operators
list braces
Detailed Description
Syntax highlighter for the Python language.
Constructor & Destructor Documentation
def software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.__init__ (self, document)
    def __init__(self, document):
        QSyntaxHighlighter.__init__(self, document)
        # Multi-line strings (expression, flag, style)
        # FIXME: The triple-quotes in these two lines will mess up the
        # syntax highlighting from this point onward
        self.tri_single = (QRegExp("'''"), 1, STYLES['string2'])
        self.tri_double = (QRegExp('"""'), 2, STYLES['string2'])
        rules = []
        # Keyword, operator, and brace rules
        rules += [(r'\b%s\b' % w, 0, STYLES['keyword'])
            for w in PythonHighlighter.keywords]
        rules += [(r'%s' % o, 0, STYLES['operator'])
            for o in PythonHighlighter.operators]
        rules += [(r'%s' % b, 0, STYLES['brace'])
            for b in PythonHighlighter.braces]
        # All other rules
        rules += [
            # 'self'
            (r'\bself\b', 0, STYLES['self']),
            # Double-quoted string, possibly containing escape sequences
            (r'"[^"\\]*(\\.[^"\\]*)*"', 0, STYLES['string']),
            # Single-quoted string, possibly containing escape sequences
            (r"'[^'\\]*(\\.[^'\\]*)*'", 0, STYLES['string']),
            # 'def' followed by an identifier
            (r'\bdef\b\s*(\w+)', 1, STYLES['defclass']),
            # 'class' followed by an identifier
            (r'\bclass\b\s*(\w+)', 1, STYLES['defclass']),
            # From '#' until a newline
            (r'#[^\n]*', 0, STYLES['comment']),
            # Numeric literals
            (r'\b[+-]?[0-9]+[lL]?\b', 0, STYLES['numbers']),
            (r'\b[+-]?0[xX][0-9A-Fa-f]+[lL]?\b', 0, STYLES['numbers']),
            (r'\b[+-]?[0-9]+(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?\b', 0, STYLES['numbers']),
        ]
        # Build a QRegExp for each pattern
        self.rules = [(QRegExp(pat), index, fmt)
            for (pat, index, fmt) in rules]
Member Function Documentation
def software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.highlightBlock (self, text)
Apply syntax highlighting to the given block of text.
References software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.match_multiline(), software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.rules, software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.setFormat(), software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.tri_double, and software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.tri_single.
    def highlightBlock(self, text):
        """Apply syntax highlighting to the given block of text.
        """
        # Do other syntax formatting
        for expression, nth, format in self.rules:
            index = expression.indexIn(text, 0)
            while index >= 0:
                # We actually want the index of the nth match
                index = expression.pos(nth)
                length = len(expression.cap(nth))
                self.setFormat(index, length, format)
                index = expression.indexIn(text, index + length)
        self.setCurrentBlockState(0)
        # Do multi-line strings
        in_multiline = self.match_multiline(text, *self.
      tri_single)
        if not in_multiline:
            in_multiline = self.match_multiline(text, *self.
      tri_double)
def software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.match_multiline (self, text, delimiter, in_state, style)
Do highlighting of multi-line strings. ``delimiter`` should be a
``QRegExp`` for triple-single-quotes or triple-double-quotes, and
``in_state`` should be a unique integer to represent the corresponding
state changes when inside those strings. Returns True if we're still
inside a multi-line string when this function is finished.
References software.chipwhisperer.common.traces.TraceContainerMySQL.TraceContainerMySQL.setFormat().
Referenced by software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.highlightBlock(), and software.chipwhisperer.common.ui.ProjectTextEditor.ProjectHighlighter.highlightBlock().
    def match_multiline(self, text, delimiter, in_state, style):
        """Do highlighting of multi-line strings. ``delimiter`` should be a
        ``QRegExp`` for triple-single-quotes or triple-double-quotes, and
        ``in_state`` should be a unique integer to represent the corresponding
        state changes when inside those strings. Returns True if we're still
        inside a multi-line string when this function is finished.
        """
        # If inside triple-single quotes, start at 0
        if self.previousBlockState() == in_state:
            start = 0
            add = 0
        # Otherwise, look for the delimiter on this line
        else:
            start = delimiter.indexIn(text)
            # Move past this match
            add = delimiter.matchedLength()
        # As long as there's a delimiter match on this line...
        while start >= 0:
            # Look for the ending delimiter
            end = delimiter.indexIn(text, start + add)
            # Ending delimiter on this line?
            if end >= add:
                length = end - start + add + delimiter.matchedLength()
                self.setCurrentBlockState(0)
            # No; multi-line string
            else:
                self.setCurrentBlockState(in_state)
                length = len(text) - start + add
            # Apply formatting
            self.setFormat(start, length, style)
            # Look for the next match
            start = delimiter.indexIn(text, start + length)
        # Return True if still inside a multi-line string, False otherwise
        if self.currentBlockState() == in_state:
            return True
        else:
            return False
Member Data Documentation
list software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.braces [static]
Initial value:
= [
        '\{', '\}', '\(', '\)', '\[', '\]',
    ]
list software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.keywords [static]
Initial value:
= [
        'and', 'assert', 'break', 'class', 'continue', 'def',
        'del', 'elif', 'else', 'except', 'exec', 'finally',
        'for', 'from', 'global', 'if', 'import', 'in',
        'is', 'lambda', 'not', 'or', 'pass', 'print',
        'raise', 'return', 'try', 'while', 'yield',
        'None', 'True', 'False',
    ]
list software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.operators [static]
Initial value:
= [
        '=',
        # Comparison
        '==', '!=', '<', '<=', '>', '>=',
        # Arithmetic
        '\+', '-', '\*', '/', '//', '\%', '\*\*',
        # In-place
        '\+=', '-=', '\*=', '/=', '\%=',
        # Bitwise
        '\^', '\|', '\&', '\~', '>>', '<<',
    ]
software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.rules
Referenced by software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.highlightBlock(), and software.chipwhisperer.common.ui.ProjectTextEditor.ProjectHighlighter.highlightBlock().
software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.tri_double
Referenced by software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.highlightBlock(), and software.chipwhisperer.common.ui.ProjectTextEditor.ProjectHighlighter.highlightBlock().
software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.tri_single
Referenced by software.chipwhisperer.analyzer.utils.syntaxhighlighter.PythonHighlighter.highlightBlock(), and software.chipwhisperer.common.ui.ProjectTextEditor.ProjectHighlighter.highlightBlock().
The documentation for this class was generated from the following file:
syntaxhighlighter.py