software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI Class Reference
Public Member Functions
def findCWSPI
def sendHID
def sendSPI (self, data)
def jumpBootloader (self)
Public Attributes
hdev
Static Public Attributes
int CMDSPI = 0x01
int CMDBOOT = 0xFE
Member Function Documentation
def software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.findCWSPI (self, VID = 0x03EB, PID = 0xBAED)
    def findCWSPI(self, VID=0x03EB, PID=0xBAED):
        print "Detecting HID device..."
        self.hdev = hid.device(VID, PID)
        print "Manufacturer: %s" % self.hdev.get_manufacturer_string()
        print "Product: %s" % self.hdev.get_product_string()
def software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.jumpBootloader (self)
References software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.CMDBOOT, and software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.sendHID().
    def jumpBootloader(self):
        self.sendHID(self.CMDBOOT)
def software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.sendHID (self, cmd, data = [])
References software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.hdev.
Referenced by software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.jumpBootloader(), and software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.sendSPI().
    def sendHID(self, cmd, data=[]):
        # Report is 64 bytes. -2 for our bytes
        padding = 64 - 2 - len(data)
        # Generate the message to pass to the stack
        hidmsg = []
        # Report ID is first byte (only 1 report here)
        hidmsg.append(0x00)
        # Command
        hidmsg.append(cmd)
        # Length of Payload (if applicable)
        hidmsg.append(len(data))
        # Payload padded to correct size
        hidmsg = hidmsg + data
        hidmsg = hidmsg + [0] * padding
        # Pass onward
        if self.hdev == None:
            return
        elif self.hdev != 2:
        # else:
            # print "HID Write: ",
            # for i in hidmsg:
            # print "0x%02x"%i,
            # print ""
            if self.hdev.write(hidmsg) < 0:
                raise IOError("Error calling hdev.write()")
def software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.sendSPI (self, data)
References software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.CMDSPI, and software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.sendHID().
    def sendSPI(self, data):
        self.sendHID(self.CMDSPI, data)
        data = self.hdev.read(65)
        if data[0] & 0x80:
            plen = data[0] & 0x7F
            results = data[1:(1 + plen)]
        else:
            raise IOError("Invalid input HID Report")
        # print results
        return results
Member Data Documentation
int software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.CMDBOOT = 0xFE [static]
Referenced by software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.jumpBootloader().
int software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.CMDSPI = 0x01 [static]
Referenced by software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.sendSPI().
software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.hdev
Referenced by software.chipwhisperer.capture.targets.ChipWhispererSPI.HIDSPI.sendHID().
The documentation for this class was generated from the following file:
ChipWhispererSPI.py