software.chipwhisperer.common.utils.aes_cipher.AESCipher Class Reference
Public Member Functions
def __init__ (self, expanded_key)
def cipher_block (self, state)
def decipher_block (self, state)
Detailed Description
Perform single block AES cipher/decipher
Constructor & Destructor Documentation
def software.chipwhisperer.common.utils.aes_cipher.AESCipher.__init__ (self, expanded_key)
References software.chipwhisperer.common.utils.aes_cipher.AESCipher._expanded_key, software.chipwhisperer.common.utils.aes_cipher.AESCipher._i_shift_row(), software.chipwhisperer.common.utils.aes_cipher.AESCipher._mix_column(), software.chipwhisperer.common.utils.aes_cipher.AESCipher._Nr, and software.chipwhisperer.common.utils.aes_cipher.AESCipher._shift_row().
    def __init__ (self, expanded_key):
        #Store epanded key
        self._expanded_key = expanded_key
        #Number of rounds determined by expanded key length
        self._Nr = int(len(expanded_key) / 16) - 1
Member Function Documentation
def software.chipwhisperer.common.utils.aes_cipher.AESCipher.cipher_block (self, state)
Perform AES block cipher on input
References software.chipwhisperer.common.utils.aes_cipher.AESCipher._add_round_key(), software.chipwhisperer.common.utils.aes_cipher.AESCipher._mix_columns(), software.chipwhisperer.common.utils.aes_cipher.AESCipher._Nr, software.chipwhisperer.common.utils.aes_cipher.AESCipher._shift_rows(), and software.chipwhisperer.common.utils.aes_cipher.AESCipher._sub_bytes().
    def cipher_block (self, state):
        """Perform AES block cipher on input"""
        #PKCS7 Padding
        state=state+[16-len(state)]*(16-len(state))#Fails test if it changes the input with +=
        self._add_round_key(state, 0)
        for i in range(1, self._Nr):
            self._sub_bytes(state)
            self._shift_rows(state)
            self._mix_columns(state, False)
            self._add_round_key(state, i)
        self._sub_bytes(state)
        self._shift_rows(state)
        self._add_round_key(state, self._Nr)
        return state
def software.chipwhisperer.common.utils.aes_cipher.AESCipher.decipher_block (self, state)
Perform AES block decipher on input
References software.chipwhisperer.common.utils.aes_cipher.AESCipher._add_round_key(), software.chipwhisperer.common.utils.aes_cipher.AESCipher._i_shift_rows(), software.chipwhisperer.common.utils.aes_cipher.AESCipher._i_sub_bytes(), software.chipwhisperer.common.utils.aes_cipher.AESCipher._mix_columns(), and software.chipwhisperer.common.utils.aes_cipher.AESCipher._Nr.
    def decipher_block (self, state):
        """Perform AES block decipher on input"""
        #null padding. Padding actually should not be needed here with valid input.
        state=state+[0]*(16-len(state))
        self._add_round_key(state, self._Nr)
        for i in range(self._Nr - 1, 0, -1):
            self._i_shift_rows(state)
            self._i_sub_bytes(state)
            self._add_round_key(state, i)
            self._mix_columns(state, True)
        self._i_shift_rows(state)
        self._i_sub_bytes(state)
        self._add_round_key(state, 0)
        return state
The documentation for this class was generated from the following file:
aes_cipher.py