software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI Class Reference
Public Member Functions
def __init__
def traceSource (self)
def setTraceSource (self, trace)
def setProject (self, proj)
def project (self)
def generate (self, trange, poiList, numPartitions)
Public Attributes
partObject
templateMeans
templateCovs
templateSource
Detailed Description
Template using Multivariate Stats (mean + covariance matrix)
Constructor & Destructor Documentation
def software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.__init__ (self, tmanager = None)
References software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI._traceSource.
    def __init__(self, tmanager=None):
        self._traceSource = None
        self.partObject = Partition(self)
Member Function Documentation
def software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.generate (self, trange, poiList, numPartitions)
Generate templates for all partitions over entire trace range
References software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.project(), and software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.traceSource().
    def generate(self, trange, poiList, numPartitions):
        """Generate templates for all partitions over entire trace range"""
        section = self.project().getDataConfig("Template Data", "Equalization Matrix")
        fname = self.project().convertDataFilepathAbs(section[0]["filename"])
        H = np.load(fname)
        # Number of subkeys
        subkeys = len(poiList)
        tstart = trange[0]
        tend = trange[1]
        templateTraces = [ [ [] for j in range(0, numPartitions) ] for i in range(0, subkeys) ]
        templateMeans = [ np.zeros(numPartitions) for i in range (0, subkeys) ]
        templateCovs = [ np.zeros(numPartitions) for i in range (0, subkeys) ]
        for tnum in range(tstart, tend):
            partData = self.traceSource().getAuxData(tnum, self.partObject.attrDictPartition)["
      filedata"]
            for bnum in range(0, subkeys):
                for i in range(0, numPartitions):
                    if tnum in partData[bnum][i]:
                        trace = self.traceSource().getTrace(tnum)
                        trace_fixed = np.dot(trace - trace.mean(), H[bnum]) + 4
                        templateTraces[bnum][i].append(trace_fixed)
            if tnum % 100 == 0:
                print tnum
        for bnum in range(0, subkeys):
            for i in range(0, numPartitions):
                templateMeans[bnum][i] = np.mean(templateTraces[bnum][i], axis=0)
                cov = np.cov(templateTraces[bnum][i], rowvar=0)
                # print "templateTraces[%d][%d] = %d" % (bnum, i, len(templateTraces[bnum][i]))
                if len(templateTraces[bnum][i]) > 0:
                    templateCovs[bnum][i] = cov
                else:
                    print "WARNING: Insufficient template data to generate covariance matrix for bnum=%d,
       partition=%d" % (bnum, i)
                    templateCovs[bnum][i] = np.zeros((len(poiList[bnum]), len(poiList[bnum])))
                # except ValueError:
                # raise ValueError("Insufficient template data to generate covariance matrix for
       bnum=%d, partition=%d" % (bnum, i))
        self.templateMeans = templateMeans
        self.templateCovs = templateCovs
        self.templateSource = (tstart, tend)
def software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.project (self)
References software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI._project.
Referenced by software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.captureM(), software.chipwhisperer.common.ui.ProjectTextEditor.ProjectTextEditor.checkGUIChanged(), software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.generate(), software.chipwhisperer.analyzer.attacks.profiling_algorithms.template.ProfilingTemplate.loadPOIs(), software.chipwhisperer.analyzer.attacks.profiling_algorithms.template.ProfilingTemplate.loadTemplatesFromProject(), software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.newProject(), software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.openProject(), software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.saveProject(), software.chipwhisperer.analyzer.attacks.profiling_algorithms.template.ProfilingTemplate.saveTemplatesToProject(), and software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.setAttack().
    def project(self):
        return self._project
def software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.setProject (self, proj)
References software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI._project.
Referenced by software.chipwhisperer.common.api.CWCoreAPI.CWCoreAPI.newProject(), and software.chipwhisperer.analyzer.attacks.profiling_algorithms.template.ProfilingTemplate.project().
    def setProject(self, proj):
        self._project = proj
def software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.setTraceSource (self, trace)
References software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI._traceSource.
    def setTraceSource(self, trace):
        self._traceSource = trace
def software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.traceSource (self)
References software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI._traceSource.
Referenced by software.chipwhisperer.analyzer.attacks.profiling_algorithms._base.TemplateBasic.generate(), software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.generate(), software.chipwhisperer.analyzer.attacks._base.AttackBaseClass.knownKey(), software.chipwhisperer.analyzer.attacks.cpa.CPA.processTraces(), and software.chipwhisperer.analyzer.attacks.profiling.Profiling.processTraces().
    def traceSource(self):
        return self._traceSource
Member Data Documentation
software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.partObject
software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.templateCovs
software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.templateMeans
software.chipwhisperer.analyzer.attacks.cpa_algorithms.experimentalchannelinfo.TemplateCSI.templateSource
The documentation for this class was generated from the following file:
experimentalchannelinfo.py