software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile Class Reference
Public Member Functions
def readHexDigit (self, in_)
def readHexByte (self, in_)
def __init__ (self, fileName)
def dataInfo (self, out)
Static Public Attributes
list ihxData = [None]
Detailed Description
generated source for class IhxFile 
Constructor & Destructor Documentation
def software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.__init__ (self, fileName)
generated source for method __init__ 
References software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.ihxData, and software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.readHexByte().
    def __init__(self, fileName):
        """ generated source for method __init__ """
        in_ = open(fileName, "r")
        b = None
        lenfield = int()
        cs = int()
        addr = int()
        buf = [None] * 255
        eof = False
        line = 0
        for i in range(0, len(self.ihxData)):
            self.ihxData[i] = -1
        try:
            while not eof:
                while b != ':':
                    b = in_.read(1)
                    if len(b) == 0: raise ValueError("Unexpected end of file")
                line += 1
                lenfield = self.readHexByte(in_)
                # length field
                cs = lenfield
                b = self.readHexByte(in_)
                # address field
                cs += b
                addr = b << 8
                b = self.readHexByte(in_)
                cs += b
                addr |= b
                b = self.readHexByte(in_)
                # record type field
                cs += b
                for i in range(0, lenfield):
                    # data
                    buf[i] = int(self.readHexByte(in_))
                    cs += buf[i]
                cs += self.readHexByte(in_)
                # checksum
                if (cs & 0xff) != 0:
                    raise ValueError("Checksum error")
                if b == 0:
                    # data record
                    for i in range(0, lenfield):
                        if self.ihxData[addr + i] >= 0:
                            print("Warning: Memory at position " + "%x" % i + " overwritten")
                        self.ihxData[addr + i] = int((buf[i] & 255))
                elif b == 1:
                    # eof record
                    eof = True
                else:
                    raise ValueError("Invalid record type: " + b)
        except ValueError as e:
            # raise IhxFileDamagedException(fileName, line, e.getLocalizedMessage())
            raise ValueError("Some Problem with decoding IHX file :(: %s" % str(e))
        try:
            in_.close()
        except Exception as e:
            print("Warning: Error closing file " + fileName + ": " + str(e))
Member Function Documentation
def software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.dataInfo (self, out)
generated source for method dataInfo 
References software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.ihxData.
    def dataInfo(self, out):
        """ generated source for method dataInfo """
        addr = -1
        i = 0
        while i <= 65536:
            # data
            if (i == 65536 or self.ihxData[i] < 0) and addr >= 0:
                print i - addr + " Bytes from " + "%x" % addr + " to " + "%x" % (i - 1)
                addr = -1
            if i < 65536 and self.ihxData[i] >= 0 and addr < 0:
                addr = i
            i += 1
def software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.readHexByte (self, in_)
generated source for method readHexByte 
References software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.readHexDigit().
Referenced by software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.__init__().
    def readHexByte(self, in_):
        """ generated source for method readHexByte """
        data = (self.readHexDigit(in_) << 4) | self.readHexDigit(in_)
        # print "%x" % data
        return data
def software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.readHexDigit (self, in_)
generated source for method readHexDigit 
Referenced by software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.readHexByte().
    def readHexDigit(self, in_):
        """ generated source for method readHexDigit """
        b = in_.read(1)
        if len(b) == 0:
            raise ValueError("Inexpected end of file")
        b = ord(b)
        if b >= ord('0') and b <= ord('9'):
            return b - ord('0')
        if b >= ord('a') and b <= ord('f'):
            return 10 + b - ord('a')
        if b >= ord('A') and b <= ord('F'):
            return 10 + b - ord('A')
        raise ValueError("Hex digit expected: " + chr(b))
Member Data Documentation
list software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.ihxData = [None] [static]
Referenced by software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.__init__(), and software.chipwhisperer.capture.scopes.cwhardware.ztex_fwloader.IhxFile.dataInfo().
The documentation for this class was generated from the following file:
ztex_fwloader.py