software.chipwhisperer.common.ui.GraphWidget.GraphWidget Class Reference
Public Member Functions
def __init__ (self)
def setDefaults (self)
def setPersistance (self, enabled)
def setColorInt
def colorPrompt (self, enabled)
def VBStateChanged (self, obj)
def VBXRangeChanged (self, vb, range)
def xRange (self)
def YDefault
def setDefaultYRange (self, lower, upper)
def setXRange (self, lower, upper)
def setYRange (self, lower, upper)
def xAutoScale (self, enabled)
def yAutoScale (self, enabled)
def xLocked (self, enabled)
def yLocked (self, enabled)
def passTrace
def clearPushed (self)
def addPersistantItem (self, item)
def checkPersistantItems (self)
def addWidget (self, widget)
def clearCustomWidgets (self)
def setLabels
def setCrossHairs (self, enabled)
def selectTrace (self, trace)
def mouseMoved (self, evt)
def setupPlot (self, plot, zOrdering, clickable, id)
Public Attributes
imagepath
selectedTrace
selectedTraceId
persistantItems
colorDialog
pw
proxysig
vLine
hLine
XLockedAction
Toolbar.
YLockedAction
actionPersistance
GraphToolbar
selection
pos
color
acolor
seedColor
autocolor
defaultYRange
persistant
lastTraceData
lastStartOffset
Static Public Attributes
tuple xRangeChanged = Signal(int, int)
tuple dataChanged = Signal(list, int)
Detailed Description
This GraphWidget holds a pyqtgraph PlotWidget, and adds a toolbar for the user to control it.
Constructor & Destructor Documentation
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.__init__ (self)
    def __init__(self):
        QWidget.__init__(self)
        pg.setConfigOption('background', 'w')
        pg.setConfigOption('foreground', 'k')
        
        self.imagepath = ":/images/"
        self.selectedTrace = None
        self.selectedTraceId = None
        self.persistantItems = []
        self._customWidgets = []
        self.colorDialog = ColorDialog()
        self.pw = pg.PlotWidget(name="Power Trace View")
        self.pw.setLabel('top', 'Power Trace View')
        self.pw.setLabel('bottom', 'Samples')
        self.pw.setLabel('left', 'Data')
        self.pw.getPlotItem().setContentsMargins(5,5,10,1)
        vb = self.pw.getPlotItem().getViewBox()
        vb.setMouseMode(vb.RectMode)
        vb.sigStateChanged.connect(self.VBStateChanged)
        vb.sigXRangeChanged.connect(self.VBXRangeChanged)
        self.proxysig = pg.SignalProxy(self.pw.plotItem.vb.scene().sigMouseMoved, rateLimit=10,
      slot=self.mouseMoved)
        self.vLine = pg.InfiniteLine(angle=90, movable=False)
        self.hLine = pg.InfiniteLine(angle=0, movable=False)
        vb.addItem(self.vLine, ignoreBounds=True)
        vb.addItem(self.hLine, ignoreBounds=True)
        ###Toolbar
        xLockedAction = QAction(QIcon(self.imagepath+'xlock.png'), 'Lock X Axis', self)
        xLockedAction.setCheckable(True)
        xLockedAction.triggered[bool].connect(self.xLocked)
        self.XLockedAction = xLockedAction
        yLockedAction = QAction(QIcon(self.imagepath+'ylock.png'), 'Lock Y Axis', self)
        yLockedAction.setCheckable(True)
        yLockedAction.triggered[bool].connect(self.yLocked)
        self.YLockedAction = yLockedAction
        yAutoScale = QAction(QIcon(self.imagepath+'yauto.png'), 'Autoscale Y Axis', self)
        yAutoScale.triggered[bool].connect(self.yAutoScale)
        xAutoScale = QAction(QIcon(self.imagepath+'xauto.png'), 'Autoscale X Axis', self)
        xAutoScale.triggered[bool].connect(self.xAutoScale)
        
        yDefault = QAction(QIcon(self.imagepath+'ydefault.png'), 'Default Y Axis', self)
        yDefault.triggered.connect(self.YDefault)
        
        self.actionPersistance = QAction(QIcon(self.imagepath+'persistance.png'),
       'Enable Persistance', self)
        self.actionPersistance.setCheckable(True)
        self.actionPersistance.triggered[bool].connect(self.setPersistance)
        
        setColour = QAction(QIcon(self.imagepath+'wavecol.png'), 'Set Colour', self)
        setColour.triggered[bool].connect(self.colorPrompt)
        
        clear = QAction(QIcon(self.imagepath+'clear.png'), 'Clear Display', self)
        clear.triggered.connect(self.clearPushed)
        crossHair = QAction(QIcon(self.imagepath+'crosshair.png'), 'Show Crosshairs', self)
        crossHair.setCheckable(True)
        crossHair.setChecked(False)
        self.setCrossHairs(crossHair.isChecked())
        crossHair.triggered.connect(lambda: self.setCrossHairs(crossHair.isChecked()))
        grid = QAction(QIcon(self.imagepath+'grid.png'), 'Show Grid', self)
        grid.setCheckable(True)
        grid.triggered.connect(lambda: self.pw.showGrid(grid.isChecked(), grid.isChecked(), 0.1))
        mouseMode = QAction(QIcon(self.imagepath+'hand.png'), 'Move', self)
        mouseMode.setCheckable(True)
        mouseMode.triggered.connect(lambda: vb.setMouseMode(
            pg.ViewBox.PanMode if mouseMode.isChecked() else pg.ViewBox.RectMode))
        help = QAction(QIcon(self.imagepath+'help.png'), 'Help', self)
        help.triggered.connect(lambda: QMessageBox.information(self, "Help",
                                "Right click or check the Results Settings for more options.\n\n"
                                "Draw types:\n"
                                "- Fast: Group traces into a min/max area;\n"
                                "- Normal: Plot all traces continuously;\n"
                                "- Detailed: Plot all traces individually.\n\n"
                                "Only highlighted traces can be selected in fast/normal."))
        self.GraphToolbar = QToolBar('Graph Tools')
        self.GraphToolbar.addAction(xLockedAction)
        self.GraphToolbar.addAction(yLockedAction)
        self.GraphToolbar.addAction(xAutoScale)
        self.GraphToolbar.addAction(yAutoScale)
        self.GraphToolbar.addAction(yDefault)
        self.GraphToolbar.addAction(self.actionPersistance)
        self.GraphToolbar.addAction(setColour)
        self.GraphToolbar.addAction(clear)
        self.GraphToolbar.addAction(crossHair)
        self.GraphToolbar.addAction(grid)
        self.GraphToolbar.addAction(mouseMode)
        self.GraphToolbar.addAction(help)
        self.GraphToolbar.addSeparator()
        self.selection = QLabel("Selected Trace: None")
        self.GraphToolbar.addWidget(self.selection)
        self.GraphToolbar.addSeparator()
        self.pos = QLabel("Position: (-, -)")
        self.GraphToolbar.addWidget(self.pos)
        layout = QVBoxLayout()
        layout.setContentsMargins(0,0,0,0)
        layout.setSpacing(0)
        layout.addWidget(self.GraphToolbar)
        layout.addWidget(self.pw)
        self.setLayout(layout)
        self.setDefaults()
Member Function Documentation
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.addPersistantItem (self, item)
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget.checkPersistantItems().
    def addPersistantItem(self, item):
        self.persistantItems.append(item)
        self.checkPersistantItems()
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.addWidget (self, widget)
References software.chipwhisperer.common.ui.ParameterTypesCustom.FilelistItem.layout.
    def addWidget(self, widget):
        self._customWidgets.append(widget)
        self.layout().addWidget(widget)
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.checkPersistantItems (self)
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget.persistantItems.
Referenced by software.chipwhisperer.common.ui.GraphWidget.GraphWidget.addPersistantItem(), and software.chipwhisperer.common.ui.GraphWidget.GraphWidget.clearPushed().
    def checkPersistantItems(self):
        for t in self.persistantItems:
            if t not in self.pw.items():
                self.pw.addItem(t)
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.clearCustomWidgets (self)
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget._customWidgets, and software.chipwhisperer.common.ui.ParameterTypesCustom.FilelistItem.layout.
    def clearCustomWidgets(self):
        for wid in self._customWidgets:
            wid.setVisible(False)
            self.layout().removeWidget(wid)
            del wid
        self._customWidgets = []
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.clearPushed (self)
Clear display
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget.acolor, software.chipwhisperer.common.ui.GraphWidget.GraphWidget.checkPersistantItems(), and software.chipwhisperer.common.ui.GraphWidget.GraphWidget.seedColor.
Referenced by software.chipwhisperer.common.results._plotdata.AttackResultPlot.drawData(), software.chipwhisperer.common.results.waveform_widget.WaveFormWidget.plotInputTrace(), and software.chipwhisperer.common.results.pgevstraceplot.PGEVsTrace.redrawPlot().
    def clearPushed(self):
        """Clear display"""
        self.pw.clear()
        self.checkPersistantItems()
        self.acolor = self.seedColor
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.colorPrompt (self, enabled)
Prompt user to set colours
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget.acolor, software.chipwhisperer.common.ui.GraphWidget.GraphWidget.autocolor, software.chipwhisperer.common.ui.GraphWidget.GraphWidget.seedColor, and software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setColorInt().
    def colorPrompt(self, enabled):
        """Prompt user to set colours"""
        if self.colorDialog.exec_():
            data = self.colorDialog.getValues()
            self.setColorInt(data[0], 9)
            self.acolor = self.seedColor = data[0]
            self.autocolor = data[1]
        
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.mouseMoved (self, evt)
    def mouseMoved(self, evt):
        mousePoint = evt[0]
        if self.pw.plotItem.vb.sceneBoundingRect().contains(mousePoint):
            pos = self.pw.plotItem.vb.mapSceneToView(mousePoint)
            self.pos.setText("Position: (%f, %f)" % (pos.x(), pos.y()))
            if self.vLine.isVisible():
                self.vLine.setPos(pos.x())
                self.hLine.setPos(pos.y())
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.passTrace (self, trace, startoffset = 0, ghostTrace = False, pen = None, idString = ``)
Plot a new trace, where X-Axis is simply 'sample number' (e.g. integer counting 0,1,2,...N-1).

:param startoffset: Offset of X-Axis, such that zero point is marked as this number
:type startoffset: int

:param ghostTrace: By default the last plotted trace is stored for use with stuff such as an overlay that
           selects data off the graph. If ghostTrace is set to 'true' the passed data is NOT stored.
:type ghostTrace: bool
Referenced by software.chipwhisperer.common.results.waveform_widget.WaveFormWidget.plotInputTrace().
    def passTrace(self, trace, startoffset=0, ghostTrace=False, pen=None, idString = ""):
        """Plot a new trace, where X-Axis is simply 'sample number' (e.g. integer counting 0,1,2,...N-1).
        :param startoffset: Offset of X-Axis, such that zero point is marked as this number
        :type startoffset: int
        :param ghostTrace: By default the last plotted trace is stored for use with stuff such as an
       overlay that
                           selects data off the graph. If ghostTrace is set to 'true' the passed data is
       NOT stored.
        :type ghostTrace: bool
        """
        if ghostTrace is False:
            self.lastTraceData = trace
            self.lastStartOffset = startoffset
        if self.persistant:
            if self.autocolor:
                nc = (self.acolor + 1) % 8
                self.acolor = nc
            else:
                self.acolor = self.color
        else:
            self.acolor = self.color
            self.pw.clear()
            
        xaxis = range(startoffset, len(trace)+startoffset)
            
        if pen is None:
            pen = pg.mkPen(self.acolor)
        p = self.pw.plot(xaxis, trace, pen=pen)
        self.setupPlot(p, 0, True, idString)
        if ghostTrace is False:
            self.dataChanged.emit(trace, startoffset)
        # TODO: This was commented out, why?
        self.checkPersistantItems()
        return p
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.selectTrace (self, trace)
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget.selectedTrace.
Referenced by software.chipwhisperer.common.results.pgevstraceplot.PGEVsTrace.redrawPlot(), and software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setupPlot().
    def selectTrace(self, trace):
        if self.selectedTrace:
            self.selectedTrace.setShadowPen(None)
        if self.selectedTrace == trace: # Deselects if the trace was already selected
            self.selectedTrace = None
            self.selection.setText("Selected Trace: None")
        else:
            self.selectedTrace = trace
            self.selectedTrace.setShadowPen(pg.mkPen(0.5, width=3, style=Qt.DashLine))
            self.selection.setText("Selected Trace: %s" % (self.selectedTrace.id if hasattr(self.
      selectedTrace, "id") else ""))
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setColorInt (self, colorint, numcolors = 16)
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget.color, and software.chipwhisperer.common.ui.CWMainGUI.OutLog.color.
Referenced by software.chipwhisperer.common.ui.GraphWidget.GraphWidget.colorPrompt().
    def setColorInt(self, colorint, numcolors=16):
        # See http://www.pyqtgraph.org/documentation/functions.html#pyqtgraph.mkColor
        self.color = pg.intColor(colorint, hues=numcolors)
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setCrossHairs (self, enabled)
    def setCrossHairs(self, enabled):
        self.vLine.setVisible(enabled)
        self.hLine.setVisible(enabled)
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setDefaults (self)
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setPersistance().
    def setDefaults(self):
        self.setPersistance(False)
        self.color = 0
        self.acolor = self.seedColor = 0
        self.autocolor = True
        self.defaultYRange = None
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setDefaultYRange (self, lower, upper)
Set default Y-Axis range, for when user clicks default button
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget.defaultYRange.
    def setDefaultYRange(self, lower, upper):
        """Set default Y-Axis range, for when user clicks default button"""
        self.defaultYRange = [lower, upper]
          
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setLabels (self, top = None, xaxis = None, yaxis = None)
Referenced by software.chipwhisperer.common.results.outputvstimeplot.OutputVsTime.__init__(), software.chipwhisperer.common.results.pgevstraceplot.PGEVsTrace.__init__(), and software.chipwhisperer.common.results.corrvstraceplot.CorrelationVsTrace.__init__().
    def setLabels(self, top=None, xaxis=None, yaxis=None):
        if top:
            self.pw.setLabel('top', top)
        if xaxis:
            self.pw.setLabel('bottom', xaxis)
        if yaxis:
            self.pw.setLabel('left', yaxis)
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setPersistance (self, enabled)
Enable Persistance mode, which means display NOT cleared before new traces added
Referenced by software.chipwhisperer.common.results.waveform_widget.WaveFormWidget.plotInputTrace(), and software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setDefaults().
    def setPersistance(self, enabled):
        """Enable Persistance mode, which means display NOT cleared before new traces added"""
        self.actionPersistance.setChecked(enabled)
        self.persistant = enabled
        
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setupPlot (self, plot, zOrdering, clickable, id)
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget.selectTrace().
Referenced by software.chipwhisperer.common.results._plotdata.AttackResultPlot.drawData().
    def setupPlot(self, plot, zOrdering, clickable, id):
        plot.setZValue(zOrdering)
        plot.id = id
        if clickable:
            plot.curve.setClickable(clickable)
            plot.sigClicked.connect(self.selectTrace)
        return plot
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setXRange (self, lower, upper)
Set the X Axis to extend from lower to upper
    def setXRange(self, lower, upper):
        """Set the X Axis to extend from lower to upper"""
        self.pw.getPlotItem().getViewBox().setXRange(lower, upper)
        
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setYRange (self, lower, upper)
Set the Y Axis to extend from lower to upper
Referenced by software.chipwhisperer.common.ui.GraphWidget.GraphWidget.YDefault().
    def setYRange(self, lower, upper):
        """Set the Y Axis to extend from lower to upper"""
        self.pw.getPlotItem().getViewBox().setYRange(lower, upper)
          
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.VBStateChanged (self, obj)
Called when ViewBox state changes, used to sync X/Y AutoScale buttons
    def VBStateChanged(self, obj):
        """Called when ViewBox state changes, used to sync X/Y AutoScale buttons"""
        arStatus = self.pw.getPlotItem().getViewBox().autoRangeEnabled()
        
        #X Axis
        if arStatus[0]:
            self.XLockedAction.setChecked(False)
        else:
            self.XLockedAction.setChecked(True)
            
        #Y Axis
        if arStatus[1]:
            self.YLockedAction.setChecked(False)
        else:
            self.YLockedAction.setChecked(True)
            
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.VBXRangeChanged (self, vb, range)
Called when X-Range changed
    def VBXRangeChanged(self, vb, range):
        """Called when X-Range changed"""
        self.xRangeChanged.emit(range[0], range[1])
        
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.xAutoScale (self, enabled)
Auto-fit X axis to data
    def xAutoScale(self, enabled):
        """Auto-fit X axis to data"""
        vb = self.pw.getPlotItem().getViewBox()
        bounds = vb.childrenBoundingRect(None)
        # print bounds
        vb.setXRange(bounds.left(), bounds.right())
        
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.xLocked (self, enabled)
Lock X axis, such it doesn't change with new data
    def xLocked(self, enabled):
        """Lock X axis, such it doesn't change with new data"""
        self.pw.getPlotItem().getViewBox().enableAutoRange(pg.ViewBox.XAxis, not enabled)
        
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.xRange (self)
Returns the X-Range
    def xRange(self):
        """Returns the X-Range"""
        return self.pw.getPlotItem().getViewBox().viewRange()[0]
            
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.yAutoScale (self, enabled)
Auto-fit Y axis to data
    def yAutoScale(self, enabled):
        """Auto-fit Y axis to data"""
        vb = self.pw.getPlotItem().getViewBox()
        bounds = vb.childrenBoundingRect(None)
        vb.setYRange(bounds.top(), bounds.bottom())
        
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.YDefault (self, extraarg = None)
Copy default Y range axis to active view
References software.chipwhisperer.common.ui.GraphWidget.GraphWidget.defaultYRange, and software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setYRange().
    def YDefault(self, extraarg=None):
        """Copy default Y range axis to active view"""
        if self.defaultYRange is not None:
            self.setYRange(self.defaultYRange[0], self.
      defaultYRange[1])
          
def software.chipwhisperer.common.ui.GraphWidget.GraphWidget.yLocked (self, enabled)
Lock Y axis, such it doesn't change with new data
    def yLocked(self, enabled):
        """Lock Y axis, such it doesn't change with new data"""
        self.pw.getPlotItem().getViewBox().enableAutoRange(pg.ViewBox.YAxis, not enabled)
        
Member Data Documentation
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.acolor
Referenced by software.chipwhisperer.common.ui.GraphWidget.GraphWidget.clearPushed(), and software.chipwhisperer.common.ui.GraphWidget.GraphWidget.colorPrompt().
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.actionPersistance
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.autocolor
Referenced by software.chipwhisperer.common.ui.GraphWidget.GraphWidget.colorPrompt().
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.color
Referenced by software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setColorInt().
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.colorDialog
tuple software.chipwhisperer.common.ui.GraphWidget.GraphWidget.dataChanged = Signal(list, int) [static]
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.defaultYRange
Referenced by software.chipwhisperer.common.ui.GraphWidget.GraphWidget.setDefaultYRange(), and software.chipwhisperer.common.ui.GraphWidget.GraphWidget.YDefault().
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.GraphToolbar
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.hLine
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.imagepath
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.lastStartOffset
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.lastTraceData
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.persistant
Referenced by software.chipwhisperer.common.results.waveform_widget.WaveFormWidget.plotInputTrace().
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.persistantItems
Referenced by software.chipwhisperer.common.ui.GraphWidget.GraphWidget.checkPersistantItems().
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.pos
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.proxysig
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.pw
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.seedColor
Referenced by software.chipwhisperer.common.ui.GraphWidget.GraphWidget.clearPushed(), and software.chipwhisperer.common.ui.GraphWidget.GraphWidget.colorPrompt().
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.selectedTrace
Referenced by software.chipwhisperer.common.ui.GraphWidget.GraphWidget.selectTrace().
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.selectedTraceId
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.selection
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.vLine
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.XLockedAction
Toolbar.
tuple software.chipwhisperer.common.ui.GraphWidget.GraphWidget.xRangeChanged = Signal(int, int) [static]
software.chipwhisperer.common.ui.GraphWidget.GraphWidget.YLockedAction
The documentation for this class was generated from the following file:
GraphWidget.py