software.chipwhisperer.common.ui.HelpWindow Namespace Reference
Classes
class HelpBrowser
Functions
def html_parts
def html_body
Variables
tuple app = QApplication(sys.argv)
tuple wid = QWidget()
tuple test = html_body(unicode(`test\n=====\n\nHello There.`))
tuple view = QtWebKit.QWebView(None)
tuple layoutmain = QHBoxLayout()
Function Documentation
def software.chipwhisperer.common.ui.HelpWindow.html_body (input_string, source_path = None, destination_path = None, input_encoding = 'unicode', output_encoding = 'unicode', doctitle = True, initial_header_level = 1)
Given an input string, returns an HTML fragment as a string.
The return value is the contents of the <body> element.
Parameters (see `html_parts()` for the remainder):

- `output_encoding`: The desired encoding of the output.  If a Unicode
  string is desired, use the default value of "unicode" .
References software.chipwhisperer.common.ui.HelpWindow.html_parts().
Referenced by software.chipwhisperer.common.ui.HelpWindow.html_parts(), and software.chipwhisperer.common.ui.HelpWindow.HelpBrowser.showHelp().
              doctitle=True, initial_header_level=1):
    """
    Given an input string, returns an HTML fragment as a string.
    The return value is the contents of the <body> element.
    Parameters (see `html_parts()` for the remainder):
    - `output_encoding`: The desired encoding of the output. If a Unicode
      string is desired, use the default value of "unicode" .
    """
    parts = html_parts(
        input_string=input_string, source_path=source_path,
        destination_path=destination_path,
        input_encoding=input_encoding, doctitle=doctitle,
        initial_header_level=initial_header_level)
    fragment = parts['html_body']
    if output_encoding != 'unicode':
        fragment = fragment.encode(output_encoding)
    return fragment
def software.chipwhisperer.common.ui.HelpWindow.html_parts (input_string, source_path = None, destination_path = None, input_encoding = 'unicode', doctitle = True, initial_header_level = 1)
Given an input string, returns a dictionary of HTML document parts.

Dictionary keys are the names of parts, and values are Unicode strings;
encoding is up to the client.

Parameters:

- `input_string`: A multi-line text string; required.
- `source_path`: Path to the source file or object.  Optional, but useful
  for diagnostic output (system messages).
- `destination_path`: Path to the file or object which will receive the
  output; optional.  Used for determining relative paths (stylesheets,
  source links, etc.).
- `input_encoding`: The encoding of `input_string`.  If it is an encoded
  8-bit string, provide the correct encoding.  If it is a Unicode string,
  use "unicode", the default.
- `doctitle`: Disable the promotion of a lone top-level section title to
  document title (and subsequent section title to document subtitle
  promotion); enabled by default.
- `initial_header_level`: The initial level for header elements (e.g. 1
  for "<h1>").
References software.chipwhisperer.common.ui.HelpWindow.html_body().
Referenced by software.chipwhisperer.common.ui.HelpWindow.html_body().
               initial_header_level=1):
    """
    Given an input string, returns a dictionary of HTML document parts.
    Dictionary keys are the names of parts, and values are Unicode strings;
    encoding is up to the client.
    Parameters:
    - `input_string`: A multi-line text string; required.
    - `source_path`: Path to the source file or object. Optional, but useful
      for diagnostic output (system messages).
    - `destination_path`: Path to the file or object which will receive the
      output; optional. Used for determining relative paths (stylesheets,
      source links, etc.).
    - `input_encoding`: The encoding of `input_string`. If it is an encoded
      8-bit string, provide the correct encoding. If it is a Unicode string,
      use "unicode", the default.
    - `doctitle`: Disable the promotion of a lone top-level section title to
      document title (and subsequent section title to document subtitle
      promotion); enabled by default.
    - `initial_header_level`: The initial level for header elements (e.g. 1
      for "<h1>").
    """
    overrides = {'input_encoding': input_encoding,
                 'doctitle_xform': doctitle,
                 'initial_header_level': initial_header_level}
    parts = core.publish_parts(
        source=input_string, source_path=source_path,
        destination_path=destination_path,
        writer_name='html', settings_overrides=overrides)
    return parts
Variable Documentation
tuple software.chipwhisperer.common.ui.HelpWindow.app = QApplication(sys.argv)
tuple software.chipwhisperer.common.ui.HelpWindow.layoutmain = QHBoxLayout()
tuple software.chipwhisperer.common.ui.HelpWindow.test = html_body(unicode(`test\n=====\n\nHello There.`))
tuple software.chipwhisperer.common.ui.HelpWindow.view = QtWebKit.QWebView(None)
tuple software.chipwhisperer.common.ui.HelpWindow.wid = QWidget()