software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog Class Reference
Public Member Functions
def __init__
def toggleSlowClock (self)
def reject (self)
def findFlash (self)
def readSignature
def readFuses (self)
def writeFuses (self)
def verifyFlash (self)
def writeFlash
def setUSBInterface (self, iface)
Public Attributes
avr
flashLocation
lowfuseLine
highfuseLine
extfuseLine
clockMode
statusLine
Constructor & Destructor Documentation
def software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.__init__ (self, parent = None)
    def __init__(self, parent=None):
        super(AVRProgrammerDialog, self).__init__(parent)
        # self.setWindowFlags(self.windowFlags() | Qt.WindowStaysOnTopHint)
        self.avr = AVRProgrammer()
        self.setWindowTitle("ChipWhisperer-Lite AVR Programmer")
        layout = QVBoxLayout()
        layoutFW = QHBoxLayout()
        self.flashLocation = QtFixes.QLineEdit()
        flashFileButton = QPushButton("Find")
        flashFileButton.clicked.connect(self.findFlash)
        layoutFW.addWidget(QLabel("FLASH File"))
        layoutFW.addWidget(self.flashLocation)
        layoutFW.addWidget(flashFileButton)
        layout.addLayout(layoutFW)
        self.flashLocation.setText(QSettings().value("avr-flash-location"))
        # Add buttons
        readSigBut = QPushButton("Check Signature")
        readSigBut.clicked.connect(self.readSignature)
        verifyFlashBut = QPushButton("Verify FLASH")
        verifyFlashBut.clicked.connect(self.verifyFlash)
        verifyFlashBut.setEnabled(False)
        progFlashBut = QPushButton("Erase/Program/Verify FLASH")
        progFlashBut.clicked.connect(self.writeFlash)
        layoutBut = QHBoxLayout()
        layoutBut.addWidget(readSigBut)
        layoutBut.addWidget(verifyFlashBut)
        layoutBut.addWidget(progFlashBut)
        layout.addLayout(layoutBut)
        layoutFuse = QHBoxLayout()
        readFuseBut = QPushButton("Read Fuses")
        readFuseBut.clicked.connect(self.readFuses)
        writeFuseBut = QPushButton("Write Fuses")
        writeFuseBut.clicked.connect(self.writeFuses)
        self.lowfuseLine = QtFixes.QLineEdit("?")
        self.lowfuseLine.setMaxLength(2)
        self.lowfuseLine.setFixedWidth(25)
        self.highfuseLine = QtFixes.QLineEdit("?")
        self.highfuseLine.setMaxLength(2)
        self.highfuseLine.setFixedWidth(25)
        self.extfuseLine = QtFixes.QLineEdit("?")
        self.extfuseLine.setMaxLength(2)
        self.extfuseLine.setFixedWidth(25)
        # Don't allow use to change these fuses
        self.highfuseLine.setReadOnly(True)
        self.extfuseLine.setReadOnly(True)
        layoutFuse.addWidget(readFuseBut)
        layoutFuse.addWidget(QLabel("LOW:"))
        layoutFuse.addWidget(self.lowfuseLine)
        layoutFuse.addWidget(QLabel("HIGH:"))
        layoutFuse.addWidget(self.highfuseLine)
        layoutFuse.addWidget(QLabel("EXT:"))
        layoutFuse.addWidget(self.extfuseLine)
        layoutFuse.addWidget(writeFuseBut)
        layout.addLayout(layoutFuse)
        layoutExtra = QHBoxLayout()
        self.clockMode = QPushButton("Enable Slow Clock Mode")
        self.clockMode.setCheckable(True)
        self.clockMode.clicked.connect(self.toggleSlowClock)
        layoutExtra.addWidget(self.clockMode)
        layoutExtra.addStretch()
        layout.addLayout(layoutExtra)
        # Add status stuff
        self.statusLine = QPlainTextEdit()
        self.statusLine.setReadOnly(True)
        # self.statusLine.setFixedHeight(QFontMetrics(self.statusLine.font()).lineSpacing() * 5 + 10)
        self.statusLine.append = self.statusLine.appendPlainText
        layout.addWidget(self.statusLine)
        self.avr._logging = self.statusLine.append
        # Set dialog layout
        self.setLayout(layout)
Member Function Documentation
def software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.findFlash (self)
    def findFlash(self):
        fname, _ = QFileDialog.getOpenFileName(self, 'Find FLASH File', QSettings().value("
      avr-flash-location"), '*.hex')
        if fname:
            self.flashLocation.setText(fname)
            QSettings().setValue("avr-flash-location", fname)
def software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.readFuses (self)
References software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.readSignature().
    def readFuses(self):
        try:
            self.readSignature(close=False)
            self.statusLine.append("Reading fuses")
            lfuse = self.avr.avr.readFuse("low")
            hfuse = self.avr.avr.readFuse("high")
            efuse = self.avr.avr.readFuse("extended")
            self.statusLine.append("OK: %02x %02x %02x" % (lfuse, hfuse, efuse))
            self.lowfuseLine.setText("%02x" % lfuse)
            self.highfuseLine.setText("%02x" % hfuse)
            self.extfuseLine.setText("%02x" % efuse)
        except IOError:
            self.statusLine.append("Reading fuses failed")
            self.lowfuseLine.setText("?")
            self.highfuseLine.setText("?")
            self.extfuseLine.setText("?")
            self.avr.close()
def software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.readSignature (self, close = True)
Referenced by software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.readFuses(), software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.writeFlash(), and software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.writeFuses().
    def readSignature(self, close=True):
        self.avr.find()
        if close:
            self.avr.close()
def software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.reject (self)
References software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.toggleSlowClock().
Referenced by software.chipwhisperer.common.ui.TraceManagerImport.TraceManagerImport.abort().
    def reject(self):
        #Ensure we disable slow-clock mode
        if self.clockMode.isChecked():
            self.clockMode.setChecked(False)
            self.toggleSlowClock()
            
        #Release AVR
        self.avr.close()
        QDialog.reject(self)
def software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.setUSBInterface (self, iface)
    def setUSBInterface(self, iface):
        self.avr.setUSBInterface(iface)
def software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.toggleSlowClock (self)
Referenced by software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.reject().
    def toggleSlowClock(self):
        if self.clockMode.isChecked():
            self.avr.avr.enableSlowClock(True)
            self.clockMode.setText("Disable Slow Clock Mode")
        else:
            self.avr.avr.enableSlowClock(False)
            self.clockMode.setText("Enable Slow Clock Mode")
def software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.verifyFlash (self)
    def verifyFlash(self):
        self.statusLine.append("Verify not implemented")
def software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.writeFlash (self, erase = True, verify = True)
References software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.readSignature().
    def writeFlash(self, erase=True, verify=True):
        status = "FAILED"
        fname = self.flashLocation.text()
        self.statusLine.append("***Starting FLASH program process at %s***" % datetime.now().strftime('
      %H:%M:%S'))
        if (os.path.isfile(fname)):
            self.statusLine.append("File %s last changed on %s" % (fname, time.ctime(os.path.getmtime(fname
      ))))
            QCoreApplication.processEvents()
            try:
                self.statusLine.append("Entering Programming Mode")
                QCoreApplication.processEvents()
                self.readSignature(close=False)
                if erase:
                    self.statusLine.append("Erasing Chip")
                    QCoreApplication.processEvents()
                    self.avr.erase()
                    self.avr.close()
                    self.readSignature(close=False)
                QCoreApplication.processEvents()
                self.avr.program(self.flashLocation.text(), memtype="flash", verify=verify)
                QCoreApplication.processEvents()
                self.statusLine.append("Exiting programming mode")
                self.avr.close()
                QCoreApplication.processEvents()
                status = "SUCCEEDED"
            except IOError, e:
                self.statusLine.append("FAILED: %s" % str(e))
                try:
                    self.avr.close()
                except IOError:
                    pass
        else:
            self.statusLine.append("%s does not appear to be a file, check path" % fname)
        self.statusLine.append("***FLASH Program %s at %s***" % (status, datetime.now().strftime('%H:%M:%S'
      )))
def software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.writeFuses (self)
References software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.readSignature().
    def writeFuses(self):
        lfuse = int(self.lowfuseLine.text(), 16)
        # hfuse = int(self.highfuseLine.text(), 16)
        # efuse = int(self.extfuseLine.text(), 16)
        self.statusLine.append("Writing fuse: not only 'low' fuse is written, as hfuse/efuse can disable
       device\n")
        try:
            self.readSignature(close=False)
            self.avr.avr.writeFuse("low", lfuse)
            # self.avr.avr.writeFuse("high", hfuse)
            # self.avr.avr.writeFuse("extended", efuse)
            # print("%x %x %x" % (lfuse, hfuse, efuse))
            self.avr.close()
        except:
            self.avr.close()
            raise
Member Data Documentation
software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.avr
software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.clockMode
software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.extfuseLine
software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.flashLocation
software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.highfuseLine
software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.lowfuseLine
software.chipwhisperer.capture.utils.AVRProgrammer.AVRProgrammerDialog.statusLine
The documentation for this class was generated from the following file:
AVRProgrammer.py