software.chipwhisperer.common.utils.util.Signal Class Reference
Public Member Functions
def __init__ (self)
def connect (self, observer)
def disconnect (self, observer)
def emit (self, arg)
def disconnectAll (self)
Public Attributes
observers
Constructor & Destructor Documentation
def software.chipwhisperer.common.utils.util.Signal.__init__ (self)
    def __init__(self):
        self.observers = []
Member Function Documentation
def software.chipwhisperer.common.utils.util.Signal.connect (self, observer)
References software.chipwhisperer.common.utils.util.Signal.observers.
Referenced by software.chipwhisperer.common.ui.TraceManagerDialog.TraceManagerDialog.refresh().
    def connect(self, observer):
        if observer not in self.observers:
            self.observers.append(observer)
def software.chipwhisperer.common.utils.util.Signal.disconnect (self, observer)
Referenced by software.chipwhisperer.common.ui.TraceManagerDialog.TraceManagerDialog.refresh().
    def disconnect(self, observer):
        self.observers.remove(observer)
def software.chipwhisperer.common.utils.util.Signal.disconnectAll (self)
References software.chipwhisperer.common.utils.util.Signal.observers.
    def disconnectAll(self):
        self.observers = []
def software.chipwhisperer.common.utils.util.Signal.emit (self, arg)
References software.chipwhisperer.common.utils.util.Signal.observers.
Referenced by software.chipwhisperer.common.utils.util.Observable.setValue().
    def emit(self, *arg):
        for observer in self.observers:
            try:
                observer(*arg)
            except Exception as e:
                etype, value, trace = sys.exc_info()
                value = "Exceptions should not escape from observers.\nReceived %s(\"%s\") from %s." % \
                        (type(e).__name__, e, observer)
                sys.excepthook(etype, value, trace)
Member Data Documentation
software.chipwhisperer.common.utils.util.Signal.observers
Referenced by software.chipwhisperer.common.utils.util.Signal.connect(), software.chipwhisperer.common.utils.util.Signal.disconnectAll(), and software.chipwhisperer.common.utils.util.Signal.emit().
The documentation for this class was generated from the following file:
util.py