software.chipwhisperer.capture.utils.IntelHex.Record Class Reference
Public Member Functions
def data (offset, bytes)
def eof ()
def extended_segment_address (usba)
def start_segment_address (cs, ip)
def extended_linear_address (ulba)
def start_linear_address (eip)
Static Public Attributes
tuple data = staticmethod(data)
tuple eof = staticmethod(eof)
tuple extended_segment_address = staticmethod(extended_segment_address)
tuple start_segment_address = staticmethod(start_segment_address)
tuple extended_linear_address = staticmethod(extended_linear_address)
tuple start_linear_address = staticmethod(start_linear_address)
Detailed Description
Helper methods to build valid ihex records.
Member Function Documentation
def software.chipwhisperer.capture.utils.IntelHex.Record.data (offset, bytes)
Return Data record. This constructs the full record, including
the length information, the record type (0x00), the
checksum, and the offset.

@param  offset  load offset of first byte.
@param  bytes   list of byte values to pack into record.

@return         String representation of one HEX record
References software.chipwhisperer.capture.utils.IntelHex.Record.data.
    def data(offset, bytes):
        """Return Data record. This constructs the full record, including
        the length information, the record type (0x00), the
        checksum, and the offset.
        @param offset load offset of first byte.
        @param bytes list of byte values to pack into record.
        @return String representation of one HEX record
        """
        assert 0 <= offset < 65536
        assert 0 < len(bytes) < 256
        b = [len(bytes), (offset >> 8) & 0x0FF, offset & 0x0FF, 0x00] + bytes
        return Record._from_bytes(b)
def software.chipwhisperer.capture.utils.IntelHex.Record.eof ()
Return End of File record as a string.
@return         String representation of Intel Hex EOF record 
    def eof():
        """Return End of File record as a string.
        @return String representation of Intel Hex EOF record
        """
        return ':00000001FF'
def software.chipwhisperer.capture.utils.IntelHex.Record.extended_linear_address (ulba)
Return Extended Linear Address Record.
@param  ulba    Upper Linear Base Address.

@return         String representation of Intel Hex ELA record.
References software.chipwhisperer.capture.utils.IntelHex.Record.extended_linear_address.
    def extended_linear_address(ulba):
        """Return Extended Linear Address Record.
        @param ulba Upper Linear Base Address.
        @return String representation of Intel Hex ELA record.
        """
        b = [2, 0, 0, 0x04, (ulba >> 8) & 0x0FF, ulba & 0x0FF]
        return Record._from_bytes(b)
def software.chipwhisperer.capture.utils.IntelHex.Record.extended_segment_address (usba)
Return Extended Segment Address Record.
@param  usba     Upper Segment Base Address.

@return         String representation of Intel Hex USBA record.
References software.chipwhisperer.capture.utils.IntelHex.Record.extended_segment_address.
    def extended_segment_address(usba):
        """Return Extended Segment Address Record.
        @param usba Upper Segment Base Address.
        @return String representation of Intel Hex USBA record.
        """
        b = [2, 0, 0, 0x02, (usba >> 8) & 0x0FF, usba & 0x0FF]
        return Record._from_bytes(b)
def software.chipwhisperer.capture.utils.IntelHex.Record.start_linear_address (eip)
Return Start Linear Address Record.
@param  eip     32-bit linear address for the EIP register.

@return         String representation of Intel Hex SLA record.
References software.chipwhisperer.capture.utils.IntelHex.Record.start_linear_address.
    def start_linear_address(eip):
        """Return Start Linear Address Record.
        @param eip 32-bit linear address for the EIP register.
        @return String representation of Intel Hex SLA record.
        """
        b = [4, 0, 0, 0x05, (eip >> 24) & 0x0FF, (eip >> 16) & 0x0FF,
             (eip >> 8) & 0x0FF, eip & 0x0FF]
        return Record._from_bytes(b)
def software.chipwhisperer.capture.utils.IntelHex.Record.start_segment_address (cs, ip)
Return Start Segment Address Record.
@param  cs      16-bit value for CS register.
@param  ip      16-bit value for IP register.

@return         String representation of Intel Hex SSA record.
References software.chipwhisperer.capture.utils.IntelHex.Record.start_segment_address.
    def start_segment_address(cs, ip):
        """Return Start Segment Address Record.
        @param cs 16-bit value for CS register.
        @param ip 16-bit value for IP register.
        @return String representation of Intel Hex SSA record.
        """
        b = [4, 0, 0, 0x03, (cs >> 8) & 0x0FF, cs & 0x0FF,
             (ip >> 8) & 0x0FF, ip & 0x0FF]
        return Record._from_bytes(b)
Member Data Documentation
tuple software.chipwhisperer.capture.utils.IntelHex.Record.data = staticmethod(data) [static]
Referenced by software.chipwhisperer.capture.utils.IntelHex.Record.data(), software.chipwhisperer.common.utils.util.Observable.setValue(), and software.chipwhisperer.common.utils.util.Observable.value().
tuple software.chipwhisperer.capture.utils.IntelHex.Record.eof = staticmethod(eof) [static]
tuple software.chipwhisperer.capture.utils.IntelHex.Record.extended_linear_address = staticmethod(extended_linear_address) [static]
Referenced by software.chipwhisperer.capture.utils.IntelHex.Record.extended_linear_address().
tuple software.chipwhisperer.capture.utils.IntelHex.Record.extended_segment_address = staticmethod(extended_segment_address) [static]
Referenced by software.chipwhisperer.capture.utils.IntelHex.Record.extended_segment_address().
tuple software.chipwhisperer.capture.utils.IntelHex.Record.start_linear_address = staticmethod(start_linear_address) [static]
Referenced by software.chipwhisperer.capture.utils.IntelHex.Record.start_linear_address().
tuple software.chipwhisperer.capture.utils.IntelHex.Record.start_segment_address = staticmethod(start_segment_address) [static]
Referenced by software.chipwhisperer.capture.utils.IntelHex.Record.start_segment_address().
The documentation for this class was generated from the following file:
IntelHex.py