software.chipwhisperer.capture.targets._smartcard_gui.APDUFilter Class Reference
Public Member Functions
def validateAPDU (self, widget)
def eventFilter (self, widget, event)
Member Function Documentation
def software.chipwhisperer.capture.targets._smartcard_gui.APDUFilter.eventFilter (self, widget, event)
References software.chipwhisperer.capture.targets._smartcard_gui.APDUFilter.validateAPDU().
    def eventFilter(self, widget, event):
        # FocusOut event
        if event.type() == QEvent.FocusOut:
            self.validateAPDU(widget)
            # return False so that the widget will also handle the event
            # otherwise it won't focus out
            return False
        else:
            # we don't care about other events
            return False
def software.chipwhisperer.capture.targets._smartcard_gui.APDUFilter.validateAPDU (self, widget)
References software.chipwhisperer.common.utils.util.hexstr2list().
Referenced by software.chipwhisperer.capture.targets._smartcard_gui.APDUFilter.eventFilter().
    def validateAPDU(self, widget):
         
        headerstart = "<font color=red>"
        headerend = "</font>"
        
        lenstart = "<font color=blue>"
        lenend = "</font>"
        
        payloadstart = "<font color=green>"
        payloadend = "</font>"
        
        
        #APDU Changed, verify & colour-code text
        data = hexstr2list(widget.toPlainText())
        htmlstr = ""
        #Validate length - basic
        if len(data) < 5:
            fail = True
        else:
            #First four bytes are header
            htmlstr += headerstart
            header = data[0:4]
            for d in header:
                htmlstr += "%02x "%d
            htmlstr += headerend
            
            #Next is payload length or response length
            htmlstr += lenstart
            htmlstr += "%02x "%data[4]
            htmlstr += lenend
            
            plen = data[4]
            
            #Have payload
            if len(data) > 5:
                
                #Hmm... bad format!?
                if (len(data)-5) < plen:
                    print "ERROR: Header too short"
                    plen = len(data)-5
                
                payload = data[5:(5+plen)]
                
                htmlstr += payloadstart
                for d in payload:
                    htmlstr += "%02x "%d
                htmlstr += payloadend
                
                if (len(data)-5) > plen:
                    htmlstr += lenstart
                    htmlstr += "%02x "%data[plen+5]
                    htmlstr += lenend
                    
                    if (len(data)-5) != (plen+1):
                        print "ERROR: Extra data"
        
            widget.setHtml(htmlstr)
    
The documentation for this class was generated from the following file:
_smartcard_gui.py