software.chipwhisperer.common.utils.qt_tweaks.QDialog Class Reference
Public Member Functions
def show (self, args, kwargs)
Detailed Description
Makes it easy to show and raise the window at the same time
Member Function Documentation
def software.chipwhisperer.common.utils.qt_tweaks.QDialog.show (self, args, kwargs)
Referenced by software.chipwhisperer.common.utils.pluginmanager.Plugin.PluginStatusDialog.__init__(), software.chipwhisperer.common.ui.pysidegraph.TestClass.initUI(), and software.chipwhisperer.common.ui.HelpWindow.HelpBrowser.showHelp().
    def show(self, *args, **kwargs):
        super(QDialog, self).show(*args, **kwargs)
        self.raise_()
The documentation for this class was generated from the following file:
qt_tweaks.py