software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog Class Reference
Public Member Functions
def __init__ (self, parent)
def showEvent (self, event)
def setupCommonScripts (self)
def addDock
def addTraceDock (self, name)
def getGraphWidgets
COMMON SCRIPTING STUFF.
def getProgressIndicator (self)
def updateChildren (self)
def updateScripts (self)
Public Attributes
exampleScripts
graphDockList
progressBar
commonScriptParams
paramCommonScripts
params
paramTreeCommonScripts
commonScriptsDock
Detailed Description
Open dialog to explore trace properties, data graphs, etc
Constructor & Destructor Documentation
def software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.__init__ (self, parent)
References software.chipwhisperer.common.api.autoscript.AutoScript.autoScriptInit().
    def __init__(self, parent):
        QMainWindow.__init__(self, parent)
        AutoScript.__init__(self)
        self.autoScriptInit()
        self.setWindowTitle("Trace Explorer")
        self.setObjectName("Trace Explorer")
        self.setCentralWidget(None)
        # Add example scripts to this list
        self.exampleScripts = [PartitionDisplay(self), TextDisplay(self)]
        # Add Scripts
        self.setupCommonScripts()
        self.graphDockList = []
        self.getGraphWidgets(["Basic Plot"])
        self.progressBar = ProgressBar(show=False)
        #self.progressBar.setWindowModality(Qt.WindowModal)
Member Function Documentation
def software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.addDock (self, dockWidget, name = `Settings`, area = Qt.LeftDockWidgetArea, allowedAreas = Qt.AllDockWidgetAreas)
Referenced by software.chipwhisperer.common.ui.CWMainGUI.CWMainGUI.addPythonConsole(), software.chipwhisperer.common.ui.CWMainGUI.CWMainGUI.addSettings(), software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.addTraceDock(), and software.chipwhisperer.common.ui.CWMainGUI.CWMainGUI.newResultWidget().
    def addDock(self, dockWidget, name="Settings", area=Qt.LeftDockWidgetArea,
      allowedAreas=Qt.AllDockWidgetAreas):
        # Configure dock
        dock = QDockWidget(name)
        dock.setAllowedAreas(allowedAreas)
        dock.setWidget(dockWidget)
        dock.setObjectName(name)
        self.addDockWidget(area, dock)
        return dock
def software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.addTraceDock (self, name)
Add a new GraphWidget in a dock, you can get the GW with .widget() property of returned QDockWidget
References software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.addDock().
Referenced by software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.getGraphWidgets().
    def addTraceDock(self, name):
        """Add a new GraphWidget in a dock, you can get the GW with .widget() property of returned
       QDockWidget"""
        return self.addDock(GraphWidget(), name=name, area=Qt.RightDockWidgetArea)
def software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.getGraphWidgets (self, nameList = [`Unknown`])
COMMON SCRIPTING STUFF.
Setup graph widgets (e.g. graphs) in the Window, and return a reference to them
References software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.addTraceDock(), and software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.graphDockList.
    def getGraphWidgets(self, nameList=["Unknown"]):
        """Setup graph widgets (e.g. graphs) in the Window, and return a reference to them"""
        # Close/Clear all widgets
        for gd in self.graphDockList:
            gd.close()
            gd.widget().clearPushed()
            gd.widget().clearCustomWidgets()
            gd.widget().setDefaults()
        for i in range(0, min(len(self.graphDockList), len(nameList))):
            self.graphDockList[i].show()
        while len(self.graphDockList) < len(nameList):
            self.graphDockList.append(self.addTraceDock("TempName"))
        for i, name in enumerate(nameList):
            self.graphDockList[i].setObjectName(name)
            self.graphDockList[i].setWindowTitle(name)
        widgetList = []
        for gd in self.graphDockList:
            widgetList.append(gd.widget())
        return widgetList
def software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.getProgressIndicator (self)
References software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.progressBar.
    def getProgressIndicator(self):
        return self.progressBar
def software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.setupCommonScripts (self)
    def setupCommonScripts(self):
        # Setup parameer tree
        self.commonScriptParams = []
        for example in self.exampleScripts:
            self.commonScriptParams.append({'name':example.name, 'type':'group', 'children':example.params}
      )
            example.scriptsUpdated.connect(self.updateScripts)
            example.runScriptFunction.connect(self.runScriptFunction.emit)
        self.paramCommonScripts = ConfigParameter.create_extended(self, name='Common
       Scripts', type='group', children=self.commonScriptParams)
        self.params = self.paramCommonScripts
        self.paramTreeCommonScripts = ParameterTree()
        self.paramTreeCommonScripts.setParameters(self.paramCommonScripts, showTop=False)
        self.commonScriptsDock = self.addDock(self.
      paramTreeCommonScripts, "Common Scipts", area=Qt.LeftDockWidgetArea)
        self.updateScripts()
def software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.showEvent (self, event)
References software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.updateChildren().
    def showEvent(self, event):
        QMainWindow.showEvent(self, event)
        self.updateChildren()
def software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.updateChildren (self)
References software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.exampleScripts, and software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.updateScripts().
Referenced by software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.showEvent().
    def updateChildren(self):
        for example in self.exampleScripts:
            if hasattr(example, 'updateScript'):
                example.updateScript("traceexplorer_show")
        self.updateScripts()
def software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.updateScripts (self)
References software.chipwhisperer.common.api.autoscript.AutoScript._smartstatements, software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.exampleScripts, and software.chipwhisperer.common.api.autoscript.AutoScript.importsAppend().
Referenced by software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.updateChildren().
    def updateScripts(self):
        for index, example in enumerate(self.exampleScripts):
            if hasattr(example, "_smartstatements"):
                for k in example._smartstatements:
                    statements = example.getStatements(k)
                    if len(statements) > 0:
                        prefix = example.__class__.__name__ + "_"
                        self._smartstatements[prefix + k] = example._smartstatements[k]
                        self._smartstatements[prefix + k].addSelfReplacement("exampleScripts[%d]." % index)
                for k in example.getImportStatements():
                    self.importsAppend(k)
        self.scriptsUpdated.emit()
Member Data Documentation
software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.commonScriptParams
software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.commonScriptsDock
software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.exampleScripts
Referenced by software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.updateChildren(), and software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.updateScripts().
software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.graphDockList
Referenced by software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.getGraphWidgets().
software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.paramCommonScripts
software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.params
Referenced by software.chipwhisperer.common.api.ExtendedParameter.ExtendedParameter.findParam(), software.chipwhisperer.capture.scopes._OpenADCInterface.OpenADCSettings.parameters(), software.chipwhisperer.common.utils.parameters.Parameterized.paramList(), software.chipwhisperer.analyzer.attacks.cpa.CPA.paramList(), software.chipwhisperer.analyzer.attacks.profiling.Profiling.paramList(), software.chipwhisperer.capture.scopes.cwhardware.ChipWhispererSAD.ChipWhispererSAD.paramList(), software.chipwhisperer.analyzer.attacks._generic_parameters.AttackGenericParameters.paramList(), software.chipwhisperer.capture.utils.GlitchExplorerDialog.GlitchExplorerDialog.paramList(), software.chipwhisperer.capture.scopes.cwhardware.ChipWhispererDigitalPattern.ChipWhispererDigitalPattern.paramList(), software.chipwhisperer.common.api.ExtendedParameter.submodule.paramList(), software.chipwhisperer.common.api.ExtendedParameter.module.paramList(), software.chipwhisperer.common.api.ExtendedParameter.maintest.paramList(), and software.chipwhisperer.common.api.ExtendedParameter.ExtendedParameter.paramTreeChanged().
software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.paramTreeCommonScripts
software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.progressBar
Referenced by software.chipwhisperer.analyzer.utils.TraceExplorerDialog.TraceExplorerDialog.getProgressIndicator().
The documentation for this class was generated from the following file:
TraceExplorerDialog.py