software.chipwhisperer.capture.utils.IntelHex Namespace Reference
Classes
class _BadFileNotation
class _DeprecatedParam
class _EndOfFile
class AddressOverlapError
class BadAccess16bit
class DuplicateStartAddressRecordError
class EmptyIntelHexError
class EOFRecordError
class ExtendedAddressRecordError
class ExtendedLinearAddressRecordError
class ExtendedSegmentAddressRecordError
class HexReaderError
class HexRecordError
class IntelHex
class IntelHex16bit
class IntelHexError
class InvalidStartAddressValueError
class NotEnoughDataError
class Record
class RecordChecksumError
class RecordLengthError
class RecordTypeError
class StartAddressRecordError
class StartLinearAddressRecordError
class StartSegmentAddressRecordError
Functions
def dict_keys (dikt)
def dict_keys_g (dikt)
def dict_items_g (dikt)
def hex2bin
def bin2hex
def diff_dumps
Variables
string __docformat__ = `javadoc`
asbytes = str
asstr = str
tuple IntTypes = (int, long)
StrType = basestring
UnicodeType = unicode
range_g = xrange
range_l = range
BytesIO = StringIO
tuple _DEPRECATED = _DeprecatedParam()
Function Documentation
def software.chipwhisperer.capture.utils.IntelHex.bin2hex (fin, fout, offset = 0)
Simple bin-to-hex convertor.
@return     0   if all OK

@param  fin     input bin file (filename or file-like object)
@param  fout    output hex file (filename or file-like object)
@param  offset  starting address offset for loading bin
def bin2hex(fin, fout, offset=0):
    """Simple bin-to-hex convertor.
    @return 0 if all OK
    @param fin input bin file (filename or file-like object)
    @param fout output hex file (filename or file-like object)
    @param offset starting address offset for loading bin
    """
    h = IntelHex()
    try:
        h.loadbin(fin, offset)
    except IOError, e:
        txt = 'ERROR: unable to load bin file:', str(e)
        print(txt)
        return 1
    try:
        h.tofile(fout, format='hex')
    except IOError, e:
        txt = "ERROR: Could not write to file: %s: %s" % (fout, str(e))
        print(txt)
        return 1
    return 0
# /def bin2hex
def software.chipwhisperer.capture.utils.IntelHex.dict_items_g (dikt)
def dict_items_g(dikt): # dict items generator
    return dikt.items()
def software.chipwhisperer.capture.utils.IntelHex.dict_keys (dikt)
Referenced by software.chipwhisperer.capture.utils.IntelHex.IntelHex.__delitem__(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.__getitem__(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.__len__(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.addresses(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.dump(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.maxaddr(), software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.maxaddr(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.minaddr(), software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.minaddr(), and software.chipwhisperer.capture.utils.IntelHex.IntelHex.write_hex_file().
def dict_keys(dikt): # dict keys list
    return dikt.keys()
def software.chipwhisperer.capture.utils.IntelHex.dict_keys_g (dikt)
Referenced by software.chipwhisperer.capture.utils.IntelHex.IntelHex.fromdict().
def dict_keys_g(dikt): # dict keys generator
    return dikt.keys()
def software.chipwhisperer.capture.utils.IntelHex.diff_dumps (ih1, ih2, tofile = None, name1 = `a`, name2 = `b`, n_context = 3)
Diff 2 IntelHex objects and produce unified diff output for their
hex dumps.

@param ih1        first IntelHex object to compare
@param ih2        second IntelHex object to compare
@param tofile     file-like object to write output
@param name1      name of the first hex file to show in the diff header
@param name2      name of the first hex file to show in the diff header
@param n_context  number of context lines in the unidiff output
def diff_dumps(ih1, ih2, tofile=None, name1="a", name2="b", n_context=3):
    """Diff 2 IntelHex objects and produce unified diff output for their
    hex dumps.
    @param ih1 first IntelHex object to compare
    @param ih2 second IntelHex object to compare
    @param tofile file-like object to write output
    @param name1 name of the first hex file to show in the diff header
    @param name2 name of the first hex file to show in the diff header
    @param n_context number of context lines in the unidiff output
    """
    def prepare_lines(ih):
        sio = StringIO()
        ih.dump(sio)
        dump = sio.getvalue()
        lines = dump.splitlines()
        return lines
    a = prepare_lines(ih1)
    b = prepare_lines(ih2)
    import difflib
    result = list(difflib.unified_diff(a, b, fromfile=name1, tofile=name2, n=n_context, lineterm=''))
    if tofile is None:
        tofile = sys.stdout
    output = '\n'.join(result) + '\n'
    tofile.write(output)
def software.chipwhisperer.capture.utils.IntelHex.hex2bin (fin, fout, start = None, end = None, size = None, pad = None)
Hex-to-Bin convertor engine.
@return     0   if all OK

@param  fin     input hex file (filename or file-like object)
@param  fout    output bin file (filename or file-like object)
@param  start   start of address range (optional)
@param  end     end of address range (inclusive; optional)
@param  size    size of resulting file (in bytes) (optional)
@param  pad     padding byte (optional)
def hex2bin(fin, fout, start=None, end=None, size=None, pad=None):
    """Hex-to-Bin convertor engine.
    @return 0 if all OK
    @param fin input hex file (filename or file-like object)
    @param fout output bin file (filename or file-like object)
    @param start start of address range (optional)
    @param end end of address range (inclusive; optional)
    @param size size of resulting file (in bytes) (optional)
    @param pad padding byte (optional)
    """
    try:
        h = IntelHex(fin)
    except HexReaderError, e:
        txt = "ERROR: bad HEX file: %s" % str(e)
        print(txt)
        return 1
    # start, end, size
    if size != None and size != 0:
        if end == None:
            if start == None:
                start = h.minaddr()
            end = start + size - 1
        else:
            if (end + 1) >= size:
                start = end + 1 - size
            else:
                start = 0
    try:
        if pad is not None:
            # using .padding attribute rather than pad argument to function call
            h.padding = pad
        h.tobinfile(fout, start, end)
    except IOError, e:
        txt = "ERROR: Could not write to file: %s: %s" % (fout, str(e))
        print(txt)
        return 1
    return 0
# /def hex2bin
Variable Documentation
string software.chipwhisperer.capture.utils.IntelHex.__docformat__ = `javadoc`
tuple software.chipwhisperer.capture.utils.IntelHex._DEPRECATED = _DeprecatedParam()
software.chipwhisperer.capture.utils.IntelHex.asbytes = str
Referenced by software.chipwhisperer.capture.utils.IntelHex.IntelHex.gets(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.loadbin(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.puts(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.tobinstr(), and software.chipwhisperer.capture.utils.IntelHex.IntelHex.write_hex_file().
software.chipwhisperer.capture.utils.IntelHex.asstr = str
Referenced by software.chipwhisperer.capture.utils.IntelHex.IntelHex.gets(), and software.chipwhisperer.capture.utils.IntelHex.IntelHex.write_hex_file().
software.chipwhisperer.capture.utils.IntelHex.BytesIO = StringIO
tuple software.chipwhisperer.capture.utils.IntelHex.IntTypes = (int, long)
software.chipwhisperer.capture.utils.IntelHex.range_g = xrange
Referenced by software.chipwhisperer.capture.utils.IntelHex.IntelHex.__delitem__(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.__getitem__(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.__setitem__(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.dump(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.gets(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.puts(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.tobinarray(), software.chipwhisperer.capture.utils.IntelHex.IntelHex16bit.tobinarray(), and software.chipwhisperer.capture.utils.IntelHex.IntelHex.write_hex_file().
software.chipwhisperer.capture.utils.IntelHex.range_l = range
Referenced by software.chipwhisperer.capture.utils.IntelHex.IntelHex.__setitem__(), software.chipwhisperer.capture.utils.IntelHex.IntelHex.dump(), and software.chipwhisperer.capture.utils.IntelHex.IntelHex.write_hex_file().
software.chipwhisperer.capture.utils.IntelHex.StrType = basestring
software.chipwhisperer.capture.utils.IntelHex.UnicodeType = unicode