software.chipwhisperer.common.results.save.ResultsSave Class Reference
Public Member Functions
def __init__
def analysisUpdated (self)
def processAnalysis (self)
def setEnabled (self, enabled)
Public Attributes
dataarray
Constructor & Destructor Documentation
def software.chipwhisperer.common.results.save.ResultsSave.__init__ (self, parentParam = None, name = None)
References software.chipwhisperer.common.results.save.ResultsSave._enabled, and software.chipwhisperer.common.results.save.ResultsSave._filename.
    def __init__(self, parentParam=None, name=None):
        ResultsBase.__init__(self, parentParam, name)
        AttackObserver.__init__(self)
        self._filename = None
        self._enabled = False
        self.dataarray = None
        self.params.addChildren([
            {'name':'Save Raw Results', 'type':'bool', 'value':False, 'set':self.
      setEnabled}
        ])
Member Function Documentation
def software.chipwhisperer.common.results.save.ResultsSave.analysisUpdated (self)
Stats have been updated
References software.chipwhisperer.common.results.save.ResultsSave._enabled, software.chipwhisperer.common.results.save.ResultsSave._filename, software.chipwhisperer.analyzer.attacks._base.AttackObserver._maxNumPerms(), software.chipwhisperer.analyzer.attacks._base.AttackObserver._numKeys(), software.chipwhisperer.analyzer.attacks._base.AttackObserver._numPerms(), and software.chipwhisperer.common.results.save.ResultsSave.dataarray.
Referenced by software.chipwhisperer.common.utils.analysissource.AnalysisObserver.setAnalysisSource().
    def analysisUpdated(self):
        """Stats have been updated"""
        if self._enabled == False:
            return
        attackStats = self._analysisSource.getStatistics()
        # attackStats.setKnownkey(nk)
        # attackStats.findMaximums(useAbsolute=self.useAbs)
        # attackStats.diffs[i][hypkey]
        # attackStats.diffs_tnum[i]
        if self._filename is None:
            # Generate filename
            self._filename = "tempstats_%s.npy" % datetime.now().strftime('%Y%m%d_%H%M%S')
            # Generate Array
            self.dataarray = []
        # Record max & min, used as we don't know if user wanted absolute mode or not
        tempmin = np.ndarray((self._numKeys(), self._maxNumPerms()))
        tempmax = np.ndarray((self._numKeys(), self._maxNumPerms()))
        for i in range(0, self._numKeys()):
            for j in range(0, self._numPerms(i)):
                tempmax[i][j] = np.nanmax(attackStats.diffs[i][j])
                tempmin[i][j] = np.nanmin(attackStats.diffs[i][j])
        newdata = {"tracecnt":copy.deepcopy(attackStats.diffs_tnum), "diffsmax":tempmax, "diffsmin":tempmin
      }
        self.dataarray.append(newdata)
        np.save(self._filename, self.dataarray)
def software.chipwhisperer.common.results.save.ResultsSave.processAnalysis (self)
Attack is done
References software.chipwhisperer.common.results.save.ResultsSave._filename, and software.chipwhisperer.common.results.save.ResultsSave.dataarray.
Referenced by software.chipwhisperer.common.utils.analysissource.AnalysisObserver.setAnalysisSource().
    def processAnalysis(self):
        """Attack is done"""
        self._filename = None
        self.dataarray = None
def software.chipwhisperer.common.results.save.ResultsSave.setEnabled (self, enabled)
References software.chipwhisperer.common.results.save.ResultsSave._enabled.
    def setEnabled(self, enabled):
        self._enabled = enabled
Member Data Documentation
software.chipwhisperer.common.results.save.ResultsSave.dataarray
Referenced by software.chipwhisperer.common.results.save.ResultsSave.analysisUpdated(), and software.chipwhisperer.common.results.save.ResultsSave.processAnalysis().
The documentation for this class was generated from the following file:
save.py