var namespacesoftware_1_1chipwhisperer_1_1capture_1_1utils_1_1GlitchExplorerDialog =
[
    [ "GlitchExplorerDialog", "db/d69/classsoftware_1_1chipwhisperer_1_1capture_1_1utils_1_1GlitchExplorerDialog_1_1GlitchExplorerDialog.html", "db/d69/classsoftware_1_1chipwhisperer_1_1capture_1_1utils_1_1GlitchExplorerDialog_1_1GlitchExplorerDialog" ],
    [ "TuningParameter", "dd/dac/classsoftware_1_1chipwhisperer_1_1capture_1_1utils_1_1GlitchExplorerDialog_1_1TuningParameter.html", "dd/dac/classsoftware_1_1chipwhisperer_1_1capture_1_1utils_1_1GlitchExplorerDialog_1_1TuningParameter" ]
];