software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog Class Reference
Public Member Functions
def __init__
def addMessage (self, level, module, note, fix, uuid)
def reloadTables (self)
def demoteItem (self, uuid)
def promoteItem (self, uuid)
def clearDefaultErrorLevels (self)
def numWarnings (self)
def setupLayout
Public Attributes
messageList
nWarnings
tableWarnings
tableInfos
Constructor & Destructor Documentation
def software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.__init__ (self, parent = None, onlyOkButton = False)
References software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.setupLayout().
    def __init__(self, parent=None, onlyOkButton=False):
        super(ValidationDialog, self).__init__(parent)
        self.setWindowTitle("Results of Validation Check")
        self.setObjectName("Results of Validation Check")
        # self.setWindowFlags((self.windowFlags() | Qt.CustomizeWindowHint | Qt.WindowStaysOnTopHint) &
       ~(Qt.WindowContextHelpButtonHint))
        self.setupLayout(onlyOkButton)
        self.messageList = []
        self.nWarnings = 0
Member Function Documentation
def software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.addMessage (self, level, module, note, fix, uuid)
References software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.reloadTables().
    def addMessage(self, level, module, note, fix, uuid):
        if (level != "info") and (level != "warn"):
            raise ValueError("Invalid level: %s" % level)
        self.messageList.append({"level":level, "module":module, "note":note, "fix":fix, "uuid":uuid})
        self.reloadTables()
def software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.clearDefaultErrorLevels (self)
    def clearDefaultErrorLevels(self):
        pass
def software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.demoteItem (self, uuid)
Demote item with given UUID to Info
    def demoteItem(self, uuid):
        """Demote item with given UUID to Info"""
        pass
def software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.numWarnings (self)
    def numWarnings(self):
        return self.nWarnings
def software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.promoteItem (self, uuid)
Promote item with given UUID to Warning
    def promoteItem(self, uuid):
        """Promote item with given UUID to Warning"""
        pass
def software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.reloadTables (self)
References software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.messageList, software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.nWarnings, software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.tableInfos, and software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.tableWarnings.
Referenced by software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.addMessage().
    def reloadTables(self):
        for m in self.messageList:
            # TODO: Check promote/demote table to override the default settings
            if m["level"] == "warn":
                table = self.tableWarnings
                pbtext = "Demote"
                self.nWarnings += 1
            else:
                table = self.tableInfos
                pbtext = "Promote"
        newrow = table.rowCount()
        table.insertRow(newrow)
        table.setCellWidget(newrow, 0, QTextEdit(m["module"]))
        table.setCellWidget(newrow, 1, QTextEdit(m["note"]))
        table.setCellWidget(newrow, 2, QTextEdit(m["fix"]))
        # pb = QPushButton(pbtext)
        # table.setCellWidget(newrow, 3, pb)
        # table.resizeRowsToContents()
        # table.resizeColumnsToContents()
def software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.setupLayout (self, onlyOkButton = False)
Referenced by software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.__init__().
    def setupLayout(self, onlyOkButton=False):
        self.tableWarnings = QTableWidget(0, 4)
        self.tableWarnings.setSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        self.tableWarnings.setHorizontalHeaderLabels(["Module", "Note", "Fix", "Demote"])
        self.tableWarnings.horizontalHeader().setResizeMode(QHeaderView.Stretch) #
       setStretchLastSection(True)
        self.tableInfos = QTableWidget(0, 4)
        self.tableInfos.setSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        self.tableInfos.setHorizontalHeaderLabels(["Module", "Note", "Fix", "Promote"])
        self.tableInfos.horizontalHeader().setResizeMode(QHeaderView.Stretch) #
       .setStretchLastSection(True)
        fullTable = QWidget()
        fullLayout = QVBoxLayout()
        fullTable.setLayout(fullLayout)
        fullLayout.addWidget(QLabel("Warning Messages"))
        fullLayout.addWidget(self.tableWarnings)
        fullLayout.addWidget(QLabel("Informational Messages"))
        fullLayout.addWidget(self.tableInfos)
        pbLayouts = QHBoxLayout()
        if onlyOkButton:
            okButton = QPushButton("OK")
            pbLayouts.addWidget(okButton)
            okButton.clicked.connect(self.accept)
        else:
            okButton = QPushButton("Continue Anyway")
            abortButton = QPushButton("Abort Capture")
            pbLayouts.addWidget(okButton)
            pbLayouts.addWidget(abortButton)
            okButton.clicked.connect(self.accept)
            abortButton.clicked.connect(self.reject)
        pbLayouts.addStretch()
        clearButton = QPushButton("Default Error Levels")
        clearButton.clicked.connect(self.clearDefaultErrorLevels)
        pbLayouts.addWidget(clearButton)
        fullLayout.addLayout(pbLayouts)
        self.setLayout(fullLayout)
Member Data Documentation
software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.messageList
Referenced by software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.reloadTables().
software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.nWarnings
Referenced by software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.numWarnings(), and software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.reloadTables().
software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.tableInfos
Referenced by software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.reloadTables().
software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.tableWarnings
Referenced by software.chipwhisperer.common.ui.ValidationDialog.ValidationDialog.reloadTables().
The documentation for this class was generated from the following file:
ValidationDialog.py