var namespacesoftware_1_1chipwhisperer_1_1capture_1_1targets_1_1simpleserial__readers_1_1serial =
[
    [ "SimpleSerial_serial", "dc/d08/classsoftware_1_1chipwhisperer_1_1capture_1_1targets_1_1simpleserial__readers_1_1serial_1_1SimpleSerial__serial.html", "dc/d08/classsoftware_1_1chipwhisperer_1_1capture_1_1targets_1_1simpleserial__readers_1_1serial_1_1SimpleSerial__serial" ]
];