software.chipwhisperer.common.ui.pysidegraph.pysideGraph Class Reference
Public Member Functions
def __init__
def getWidget (self)
def updateAxis (self)
def redraw (self)
def updateData
Public Attributes
gb
fig
fig_ax
xmin
xmax
ymin
ymax
Constructor & Destructor Documentation
def software.chipwhisperer.common.ui.pysidegraph.pysideGraph.__init__ (self, name = ``, xmin = 0, xmax = 1, ymin = -1.0, ymax = 1.0, xfigsize = 600, yfigsize = 600, showNav = True, showExtraSettings = False)
    def __init__(self, name="", xmin=0, xmax=1, ymin=-1.0, ymax=1.0, xfigsize=600, yfigsize=600,
      showNav=True, showExtraSettings=False):
        self.gb = QGroupBox(name)
        self.fig = Figure(figsize=(xfigsize,yfigsize), dpi=72)
        self.fig_ax = self.fig.add_subplot(111)
        self.fig_ax.plot([0,0])
        clocklayout = QVBoxLayout()
        canvas = FigureCanvas(self.fig)
        layout = QVBoxLayout()
        layout.addWidget(canvas)
        if showNav:
            ntbr = NavigationToolbar(canvas, self.gb)
            layout.addWidget(ntbr)
        if showExtraSettings:
            settingsLayout = QGridLayout()
            self.xmin = QSpinBox()
            self.xmin.setMinimum(xmin)
            self.xmin.setMaximum(xmax)
            self.xmax = QSpinBox()
            self.xmax.setMinimum(xmin)
            self.xmax.setMaximum(xmax)
            self.ymin = QDoubleSpinBox()
            self.ymin.setMinimum(ymin)
            self.ymin.setMaximum(ymax)
            self.ymin.setDecimals(5)
            self.ymax = QDoubleSpinBox()
            self.ymax.setMinimum(ymin)
            self.ymax.setMaximum(ymax)
            self.ymin.setValue(ymin)
            self.ymax.setValue(ymax)
            self.xmin.setValue(xmin)
            self.xmax.setValue(xmax)
            self.ymax.setDecimals(5)
            settingsLayout.addWidget(QLabel("X Limits:"), 0, 0)
            settingsLayout.addWidget(self.xmin, 0, 1)
            settingsLayout.addWidget(self.xmax, 0, 2)
            settingsLayout.addWidget(QLabel("Y Limits:"), 1, 0)
            settingsLayout.addWidget(self.ymin, 1, 1)
            settingsLayout.addWidget(self.ymax, 1, 2)
            #settingsLayout.addWidget(self.persistant, 1, 3)
            layout.addLayout(settingsLayout)
            self.xmin.valueChanged.connect(self.updateAxis)
            self.xmax.valueChanged.connect(self.updateAxis)
            self.ymin.valueChanged.connect(self.updateAxis)
            self.ymax.valueChanged.connect(self.updateAxis)
        else:
            self.xmin = None
            
        self.gb.setLayout(layout)
Member Function Documentation
def software.chipwhisperer.common.ui.pysidegraph.pysideGraph.getWidget (self)
References software.chipwhisperer.common.ui.pysidegraph.pysideGraph.gb.
    def getWidget(self):
        return self.gb
def software.chipwhisperer.common.ui.pysidegraph.pysideGraph.redraw (self)
Referenced by software.chipwhisperer.common.ui.pysidegraph.pysideGraph.updateAxis(), and software.chipwhisperer.common.ui.pysidegraph.pysideGraph.updateData().
    def redraw(self):
        self.fig.canvas.draw()
            
def software.chipwhisperer.common.ui.pysidegraph.pysideGraph.updateAxis (self)
References software.chipwhisperer.common.ui.pysidegraph.pysideGraph.redraw(), and software.chipwhisperer.common.ui.pysidegraph.pysideGraph.xmin.
Referenced by software.chipwhisperer.common.ui.pysidegraph.pysideGraph.updateData().
    def updateAxis(self):
        if self.xmin:
            self.fig_ax.axis([self.xmin.value(), self.xmax.value(), self.ymin.value(), self.ymax.value()])
        self.redraw()
def software.chipwhisperer.common.ui.pysidegraph.pysideGraph.updateData (self, data = None, holdOn = False, updateAxis = True, redraw = True)
References software.chipwhisperer.common.ui.pysidegraph.pysideGraph.redraw(), software.chipwhisperer.common.ui.pysidegraph.pysideGraph.updateAxis(), and software.chipwhisperer.common.ui.pysidegraph.pysideGraph.xmin.
    def updateData(self, data=None, holdOn=False, updateAxis=True, redraw=True):
        if len(data) > 0:
            if holdOn == False:
                self.fig_ax.cla()
            self.fig_ax.plot(data)
        if self.xmin:
            if self.xmin.value() == self.xmax.value():
                cursettings = self.fig_ax.axis()
                self.xmin.setValue(cursettings[0])
                self.xmax.setValue(cursettings[1])
                self.ymin.setValue(cursettings[2])
                self.ymax.setValue(cursettings[3])
            else:
                if updateAxis:
                    self.updateAxis()
        else:
            if updateAxis:
                self.updateAxis()
        if redraw:
            self.redraw()
Member Data Documentation
software.chipwhisperer.common.ui.pysidegraph.pysideGraph.fig
software.chipwhisperer.common.ui.pysidegraph.pysideGraph.fig_ax
software.chipwhisperer.common.ui.pysidegraph.pysideGraph.gb
Referenced by software.chipwhisperer.common.ui.pysidegraph.pysideGraph.getWidget().
software.chipwhisperer.common.ui.pysidegraph.pysideGraph.xmax
software.chipwhisperer.common.ui.pysidegraph.pysideGraph.xmin
Referenced by software.chipwhisperer.common.ui.pysidegraph.pysideGraph.updateAxis(), and software.chipwhisperer.common.ui.pysidegraph.pysideGraph.updateData().
software.chipwhisperer.common.ui.pysidegraph.pysideGraph.ymax
software.chipwhisperer.common.ui.pysidegraph.pysideGraph.ymin
The documentation for this class was generated from the following file:
pysidegraph.py