software.chipwhisperer.hardware.naeusb.naeusb Namespace Reference
Classes
class NAEUSB
Functions
def packuint32 (data)
def packuint16 (data)
Variables
int NEWAE_VID = 0x2B3E
dictionary NEWAE_PIDS
tuple cwtestusb = NAEUSB()
tuple fpga = FPGA(cwtestusb)
tuple xmega = XMEGAPDI(cwtestusb)
tuple avr = AVRISP(cwtestusb)
tuple usart = USART(cwtestusb)
force = True
tuple starttime = datetime.now()
tuple stoptime = datetime.now()
avrprogram = False
xmegaprogram = True
tuple data = xmega.readMemory(0x01000090, 3, `signature`)
list fakedata = [i & 0xff for i in range(0, 2048)]
tuple test = xmega.readMemory(0x0800000, 512)
sertest = True
Function Documentation
def software.chipwhisperer.hardware.naeusb.naeusb.packuint16 (data)
Converts a 16-bit integer into format expected by USB firmware
def packuint16(data):
    """Converts a 16-bit integer into format expected by USB firmware"""
    return [data & 0xff, (data >> 8) & 0xff, (data >> 16) & 0xff, (data >> 24) & 0xff]
#List of all NewAE PID's
def software.chipwhisperer.hardware.naeusb.naeusb.packuint32 (data)
Converts a 32-bit integer into format expected by USB firmware
Referenced by software.chipwhisperer.hardware.naeusb.naeusb.NAEUSB.cmdReadMem(), software.chipwhisperer.hardware.naeusb.naeusb.NAEUSB.cmdWriteMem(), software.chipwhisperer.hardware.naeusb.serial.USART.init(), software.chipwhisperer.hardware.naeusb.programmer_xmega.XMEGAPDI.readMemory(), software.chipwhisperer.hardware.naeusb.programmer_avr.AVRISP.readMemory(), software.chipwhisperer.hardware.naeusb.programmer_xmega.XMEGAPDI.setParamTimeout(), and software.chipwhisperer.hardware.naeusb.programmer_xmega.XMEGAPDI.writeMemory().
def packuint32(data):
    """Converts a 32-bit integer into format expected by USB firmware"""
    return [data & 0xff, (data >> 8) & 0xff, (data >> 16) & 0xff, (data >> 24) & 0xff]
Variable Documentation
tuple software.chipwhisperer.hardware.naeusb.naeusb.avr = AVRISP(cwtestusb)
software.chipwhisperer.hardware.naeusb.naeusb.avrprogram = False
tuple software.chipwhisperer.hardware.naeusb.naeusb.cwtestusb = NAEUSB()
tuple software.chipwhisperer.hardware.naeusb.naeusb.data = xmega.readMemory(0x01000090, 3, `signature`)
list software.chipwhisperer.hardware.naeusb.naeusb.fakedata = [i & 0xff for i in range(0, 2048)]
software.chipwhisperer.hardware.naeusb.naeusb.force = True
tuple software.chipwhisperer.hardware.naeusb.naeusb.fpga = FPGA(cwtestusb)
dictionary software.chipwhisperer.hardware.naeusb.naeusb.NEWAE_PIDS
Initial value:
= {
    0xACE2: "ChipWhisperer-Lite",
    0xC305: "CW305 Artix FPGA Board",
}
int software.chipwhisperer.hardware.naeusb.naeusb.NEWAE_VID = 0x2B3E
software.chipwhisperer.hardware.naeusb.naeusb.sertest = True
tuple software.chipwhisperer.hardware.naeusb.naeusb.starttime = datetime.now()
tuple software.chipwhisperer.hardware.naeusb.naeusb.stoptime = datetime.now()
tuple software.chipwhisperer.hardware.naeusb.naeusb.test = xmega.readMemory(0x0800000, 512)
tuple software.chipwhisperer.hardware.naeusb.naeusb.usart = USART(cwtestusb)
tuple software.chipwhisperer.hardware.naeusb.naeusb.xmega = XMEGAPDI(cwtestusb)
software.chipwhisperer.hardware.naeusb.naeusb.xmegaprogram = True